import type { DDxPresentation } from './types'

/* DIFFERENTIAL-DIAGNOSIS ENGINE presentations (§51) */

export const DDx_PRESENTATIONS: DDxPresentation[] = [
  {
    id: 'ddx-bleeding-pregnancy', presentation: 'Bleeding in pregnancy',
    redFlagsImmediate: ['Haemodynamic instability', 'Abnormal CTG / absent FHR', 'Pain + tense uterus (abruption)', 'Prior scar + bleeding (acreta/rupture)'],
    urgentWorkup: ['Two IVs + CBC/coags/crossmatch', 'CTG continuous (viable)', 'US: placental location, fetal state', 'Kleihauer if Rh-negative'],
    firstMoves: ['NO digital examination until placenta excluded', 'Declare pathway by gestation band'],
    differential: [
      { condition: 'Placenta praevia', priority: 'cannot-miss', keyFeatures: 'Painless bright bleed; malpresentation', action: 'aph-previa pathway; no PV exams', topicRef: 'aph-previa' },
      { condition: 'Placental abruption', priority: 'cannot-miss', keyFeatures: 'Painful woody uterus; DIC risk', action: 'Delivery decision dominates', topicRef: 'aph-abruption' },
      { condition: 'Vasa praevia', priority: 'cannot-miss', keyFeatures: 'Fetal bradycardia after ROM', action: 'Immediate caesarean', topicRef: 'vasa-previa' },
      { condition: 'Miscarriage (<24 wks)', priority: 'common', keyFeatures: 'Cramping + open os patterns', action: 'EPL pathways', topicRef: 'miscarriage-management' },
      { condition: 'Cervical/polyp lesion', priority: 'consider', keyFeatures: 'Speculum-visible source', action: 'Treat locally once placenta excluded' },
      { condition: 'Lower genital trauma', priority: 'consider', keyFeatures: 'History/exam findings', action: 'Repair; safeguarding if assault' },
    ],
  },
  {
    id: 'ddx-abdominal-pain-pregnancy', presentation: 'Abdominal pain in pregnancy',
    redFlagsImmediate: ['Peritonism/rigidity', 'Hypotension/tachycardia', 'Positive hCG + unilateral pain (ectopic!)', 'Fever + RUQ (HELLP/cholangitis)'],
    urgentWorkup: ['hCG FIRST in reproductive age', 'CBC, LFTs, lipase, urinalysis', 'TVS/TAS US', 'CXR/ECG when upper abdomen unclear'],
    firstMoves: ['Obstetric exclusion scan before surgical labels'],
    differential: [
      { condition: 'Ectopic pregnancy', priority: 'cannot-miss', keyFeatures: 'Amenorrhoea+pain+bleeding triad', action: 'Ectopic module', topicRef: 'ectopic-pregnancy' },
      { condition: 'Abruption', priority: 'cannot-miss', keyFeatures: 'Uterine tenderness+contractions', action: 'abruption pathway', topicRef: 'aph-abruption' },
      { condition: 'Appendicitis', priority: 'common', keyFeatures: 'Migration to RIF displaced upward with gestation', action: 'Surgical review; imaging MRI/US-first' },
      { condition: 'Ovarian torsion', priority: 'cannot-miss', keyFeatures: 'Acute vomiting+mass', action: 'Emergency laparoscopy', topicRef: 'adnexal-mass-torsion' },
      { condition: 'Pyelonephritis', priority: 'common', keyFeatures: 'Loin->groin, rigors', action: 'UTI module', topicRef: 'uti-pyelonephritis' },
      { condition: 'HELLP epigastric', priority: 'consider', keyFeatures: 'HTN+platelets/LFTs', action: 'HELLP module', topicRef: 'hdp-hellp' },
      { condition: 'Round ligament/obstetric benign', priority: 'consider', keyFeatures: 'Self-limited, afebrile', action: 'Reassure after exclusions' },
    ],
  },
  {
    id: 'ddx-reduced-fetal-movements', presentation: 'Reduced fetal movements',
    redFlagsImmediate: ['Abnormal CTG', 'Absent heartbeat on US', 'Maternal hypertension symptoms'],
    urgentWorkup: ['Immediate CTG', 'US growth/fluid/Doppler'],
    firstMoves: ['Never telephone-reassure second episodes'],
    differential: [
      { condition: 'Silent FGR', priority: 'cannot-miss', keyFeatures: 'EFW<10th + abnormal Doppler', action: 'FGR pathway', topicRef: 'fgr' },
      { condition: 'Normal variation/sleep cycle', priority: 'common', keyFeatures: 'All surveillance normal', action: 'Education + return rules', topicRef: 'reduced-fetal-movements' },
      { condition: 'Impending abruption/hypertension', priority: 'consider', keyFeatures: 'BP/proteinuria trends', action: 'HDP screen' },
    ],
  },
  {
    id: 'ddx-headache-highbp', presentation: 'Headache + high BP in pregnancy/postpartum',
    redFlagsImmediate: ['Seizure', 'Visual scotomata/drowsiness/focal deficit', 'SBP>=160/DBP>=110', 'Epigastric pain'],
    urgentWorkup: ['Confirm BP both readings', 'Platelets/LFTs/creatinine', 'Protein quantification', 'Neuro exam incl. fundi'],
    firstMoves: ['Treat BP>=160/110 within minutes-hours while differentiating'],
    differential: [
      { condition: 'Pre-eclampsia spectrum', priority: 'cannot-miss', keyFeatures: 'Organ dysfunction signs', action: 'HDP modules', topicRef: 'hdp-pre-eclampsia' },
      { condition: 'Postpartum eclampsia/CVT', priority: 'cannot-miss', keyFeatures: 'Seizure postpartum any BP', action: 'Imaging MRV consideration' },
      { condition: 'Migraine', priority: 'common', keyFeatures: 'Typical pattern, normal labs', action: 'Safe analgesics only' },
      { condition: 'Intracranial haemorrhage', priority: 'cannot-miss', keyFeatures: 'Focal deficit/coma', action: 'CT + neurosurgery' },
      { condition: 'Idiopathic intracranial hypertension', priority: 'consider', keyFeatures: 'Obese, pulsatile tinnitus, papilloedema', action: 'Fundoscopy/neuro referral' },
    ],
  },
  {
    id: 'ddx-fever-postpartum', presentation: 'Fever in pregnancy/postpartum',
    redFlagsImmediate: ['Rigors+hypotension (sepsis)', 'Retained products + uterine tenderness', 'Wound necrosis/pain out of proportion', 'Respiratory distress'],
    urgentWorkup: ['Sepsis screening bundle', 'Cultures BEFORE antibiotics', 'US for RPOC/collections'],
    firstMoves: ['Antibiotics within the hour for true sepsis physiology'],
    differential: [
      { condition: 'Endometritis/septic abortion', priority: 'cannot-miss', keyFeatures: 'Uterine tenderness+foul discharge', action: 'Sepsis module + evacuation', topicRef: 'maternal-sepsis' },
      { condition: 'Chorioamnionitis', priority: 'cannot-miss', keyFeatures: 'Intrapartum fever+foul liquor', action: 'Antibiotics+birth', topicRef: 'chorioamnionitis' },
      { condition: 'Mastitis/breast abscess', priority: 'common', keyFeatures: 'Localised breast signs', action: 'Continue feeding + antibiotics; US if fluctuant' },
      { condition: 'Pyelonephritis', priority: 'common', keyFeatures: 'Loin pain+urine pyuria', action: 'UTI module', topicRef: 'uti-pyelonephritis' },
      { condition: 'Influenza/COVID/malaria (region)', priority: 'consider', keyFeatures: 'Epidemiology+respiratory/parasite tests', action: 'Respective protocols' },
      { condition: 'Thrombophlebitis/PE', priority: 'consider', keyFeatures: 'Leg signs/chest symptoms', action: 'VTE module', topicRef: 'vte' },
    ],
  },
  {
    id: 'ddx-dyspnoea-pregnancy', presentation: 'Dyspnoea in pregnancy',
    redFlagsImmediate: ['SpO2 <95%', 'Collapse/chest pain', 'Unilateral leg swelling (PE)', 'Fine crepitations (pulmonary oedema PET)'],
    urgentWorkup: ['ABG/SpO2, ECG, CXR (safe)', 'Echo if unclear', 'CTPA/V-Q per pathway'],
    firstMoves: ['Left-lateral tilt + O2 immediately when distressed'],
    differential: [
      { condition: 'Pulmonary embolism', priority: 'cannot-miss', keyFeatures: 'Pleuritic pain+risk factors', action: 'VTE module', topicRef: 'vte' },
      { condition: 'Pulmonary oedema of severe PE/fluids', priority: 'cannot-miss', keyFeatures: 'Hypertension+crepitations', action: 'Sit up, stop fluids, frusemide' },
      { condition: 'Asthma exacerbation', priority: 'common', keyFeatures: 'Wheeze history', action: 'Full asthma treatment (undertreatment harms fetus)' },
      { condition: 'Physiological dyspnoea', priority: 'common', keyFeatures: 'Gradual, normal investigations', action: 'Diagnosis of exclusion' },
      { condition: 'Anemia severe', priority: 'consider', keyFeatures: 'Pallor, Hb <7', action: 'Anaemia module', topicRef: 'anaemia-iron-deficiency' },
      { condition: 'Amniotic fluid embolism', priority: 'cannot-miss', keyFeatures: 'Peripartum collapse+DIC', action: 'AFE protocol', topicRef: 'emg-afe' },
    ],
  },
  {
    id: 'ddx-vaginal-discharge', presentation: 'Vaginal discharge / cervicitis',
    redFlagsImmediate: ['Pelvic pain+fever (PID)', 'Pregnancy + bleeding', 'Post-surgical fistula leak (continuous urine)'],
    urgentWorkup: ['Speculum + pH/microscopy where available', 'NAAT chlamydia/gonorrhoea', 'BV/trich testing'],
    firstMoves: ['Treat PID presumptively at low threshold'],
    differential: [
      { condition: 'Bacterial vaginosis', priority: 'common', keyFeatures: 'Fishy thin discharge pH>4.5', action: 'Metronidazole course', topicRef: 'vaginitis' },
      { condition: 'Candidiasis', priority: 'common', keyFeatures: 'Itchy curdy discharge', action: 'Topical azoles (pregnancy-safe)' },
      { condition: 'Trichomoniasis', priority: 'common', keyFeatures: 'Frothy strawberry cervix', action: 'Nitroimidazole + partners' },
      { condition: 'Chlamydia/gonorrhoea cervicitis', priority: 'cannot-miss', keyFeatures: 'Mucopurulent/friction bleeding', action: 'CDC regimens + partner therapy', topicRef: 'sti-chlamydia' },
      { condition: 'Fistula (continuous leak)', priority: 'consider', keyFeatures: 'Post-obstetric surgery history', action: 'Urogynae referral', topicRef: 'urogynaecology-core' },
    ],
  },
  {
    id: 'ddx-acute-pelvic-pain-gynae', presentation: 'Acute pelvic pain (non-pregnant)',
    redFlagsImmediate: ['Peritonism', 'Adnexal mass+vomiting (torsion)', 'Positive hCG ANY context', 'TOA signs'],
    urgentWorkup: ['Urine hCG mandatory', 'TVS pelvis', 'CBC/CRP; STI NAATs'],
    firstMoves: ['Torsion and ectopic outrank all other diagnoses until excluded'],
    differential: [
      { condition: 'Ovarian torsion', priority: 'cannot-miss', keyFeatures: 'Acute+vomiting+mass', action: 'Emergency laparoscopy detorsion', topicRef: 'adnexal-mass-torsion' },
      { condition: 'Ectopic pregnancy', priority: 'cannot-miss', keyFeatures: 'hCG+', action: 'Ectopic pathway', topicRef: 'ectopic-pregnancy' },
      { condition: 'PID/TOA', priority: 'common', keyFeatures: 'Discharge+cervical motion tenderness', action: 'PID regimens ± drainage', topicRef: 'pid' },
      { condition: 'Ruptured cyst', priority: 'common', keyFeatures: 'Mid-cycle, free fluid', action: 'Conservative if stable' },
      { condition: 'Appendicitis', priority: 'common', keyFeatures: 'GI migration pattern', action: 'Surgical assessment' },
      { condition: 'Endometriosis flare', priority: 'consider', keyFeatures: 'Dysmenorrhoeic history', action: 'Endo module', topicRef: 'endometriosis' },
    ],
  },
  {
    id: 'ddx-pmb', presentation: 'Postmenopausal bleeding',
    redFlagsImmediate: ['Heavy/repeated PMB', 'On tamoxifen', 'Palpable pelvic mass', 'Suspicious cervical lesion'],
    urgentWorkup: ['TVS endometrial thickness', 'Outpatient pipelle biopsy', 'Hysteroscopy if failed/inconclusive'],
    firstMoves: ['Every PMB investigated - never assume HRT/atrophy without sampling'],
    differential: [
      { condition: 'Endometrial carcinoma/hyperplasia', priority: 'cannot-miss', keyFeatures: 'Thickened endometrium/risk profile', action: 'Oncology pathway', topicRef: 'gyonc-endometrial' },
      { condition: 'Cervical cancer', priority: 'cannot-miss', keyFeatures: 'Contact bleeding/lesion', action: 'Biopsy + staging referral', topicRef: 'gyonc-cervical' },
      { condition: 'Atrophic endometrium/vaginitis', priority: 'common', keyFeatures: 'Thin friable tissues, thin endometrium', action: 'Treat AFTER biopsy excludes malignancy' },
      { condition: 'Polyps', priority: 'common', keyFeatures: 'Focal lesion on US/saline scan', action: 'Polypectomy with histology' },
      { condition: 'HRT-related', priority: 'consider', keyFeatures: 'Regimen timing correlation', action: 'Investigate first, then adjust regimen' },
    ],
  },
  {
    id: 'ddx-infertility', presentation: 'Infertility evaluation',
    redFlagsImmediate: ['Known tubal disease + pain (hydrosalpinx/ectopic risk)', 'Postmenopausal-range FSH <40 y (POI)'],
    urgentWorkup: ['Semen analysis x2 early', 'Cycle documentation', 'AMH/AFC context', 'HSG/hyCoSy patency'],
    firstMoves: ['Couple-based workup always - never female-only'],
    differential: [
      { condition: 'Anovulation (PCOS etc.)', priority: 'common', keyFeatures: 'Irregular cycles', action: 'Letrozole-first ladder', topicRef: 'pcos' },
      { condition: 'Male factor', priority: 'common', keyFeatures: 'Abnormal semen parameters', action: 'Andrology/ART referral' },
      { condition: 'Tubal factor', priority: 'common', keyFeatures: 'HSG blockage/PID history', action: 'IVF vs surgical decisions' },
      { condition: 'Endometriosis-associated', priority: 'consider', keyFeatures: 'Pain profile', action: 'Surgery then ART timing', topicRef: 'endometriosis' },
      { condition: 'Diminished ovarian reserve', priority: 'consider', keyFeatures: 'Low AMH/AFC', action: 'Counsel + tailored stimulation', topicRef: 'infertility-female' },
    ],
  },
]
