import type { DrugRecord } from './types'

/* ============================================================
   DRUG DATABASE — pregnancy/gynae-specific
   Every dose carries its source id; entries marked status honestly.
   ============================================================ */

const P = 'published'
export const DRUGS: DrugRecord[] = [
  {
    id: 'magnesium-sulfate', name: 'Magnesium sulfate', drugClass: 'Anticonvulsant/uterorelaxant', dbCategory: 'emergency-drugs',
    indications: ['Eclampsia', 'Severe pre-eclampsia seizure prophylaxis', 'Fetal neuroprotection <30-32 wks', 'Torsades adjunct (ICU)'],
    pregnancySafety: 'Standard of care in pregnancy for above indications', trimesterNotes: 'All trimesters when indicated', lactation: 'Compatible',
    doseRows: [
      { indication: 'Eclampsia/severe PE (Pritchard)', dose: '4 g IV slow + 10 g IM loading; 5 g IM q4h maintenance', route: 'IV+IM', frequency: 'q4h maintenance', preparation: 'IV as 20% over 5-10 min; IM 50% deep gluteal' },
      { indication: 'Neuroprotection', dose: '4 g IV over 30 min then 1 g/h', route: 'IV infusion', frequency: 'Continuous until birth' },
    ],
    contraindications: ['Myasthenia gravis', 'Heart block'], interactions: ['Additive neuromuscular blockade with aminoglycosides/nifedipine caution'],
    adverseEffects: ['Flushing, weakness, diplopia, respiratory depression, cardiac arrest at toxic levels'],
    monitoring: ['Patellar reflexes', 'RR >=12/min', 'Urine output >=25 mL/h', 'Serum levels where available'],
    renalHepatic: 'Renal impairment: reduce/major caution',
    sourceId: 'fogsi-hdp-gcpr-2026', emergencyKit: true, status: P,
  },
  {
    id: 'tranexamic-acid', name: 'Tranexamic acid', drugClass: 'Antifibrinolytic', dbCategory: 'haematology-adjuncts',
    indications: ['PPH treatment (within 3 h of birth)', 'Acute AUB control', 'Trauma bleeding protocols'],
    pregnancySafety: 'Used in obstetric haemorrhage per WHO; not prophylaxis', lactation: 'Compatible',
    doseRows: [
      { indication: 'PPH', dose: '1 g IV over 10 min; repeat after 30 min if bleeding continues', route: 'IV', frequency: 'Max 2 g total', preparation: '1 g in 10 mL push at 1 mL/min' },
      { indication: 'Heavy menstrual bleeding', dose: '1 g PO QID days 1-4 of cycle', route: 'PO', frequency: 'QID x4 days', max: 'Not beyond 5 days/cycle' },
    ],
    contraindications: ['Initiation >3 h post-birth (except restart within 24 h rule)', 'Active thromboembolic disease', 'Severe renal failure caution'],
    adverseEffects: ['Nausea/diarrhoea; thromboembolism theoretical risk'],
    monitoring: ['Bleeding response', 'Never mix with blood products in same line'],
    sourceId: 'who-txa-pph-2017', emergencyKit: true, status: P,
  },
  {
    id: 'oxytocin', name: 'Oxytocin', drugClass: 'Uterotonic', dbCategory: 'uterotonics',
    indications: ['Third-stage prophylaxis', 'PPH treatment', 'Labour augmentation/induction'],
    pregnancySafety: 'Intrinsic hormone; safe appropriately used', lactation: 'Compatible',
    doseRows: [
      { indication: 'Third stage', dose: '10 IU IM/IV slow', route: 'IM/IV', frequency: 'Once (+infusion at CS)' },
      { indication: 'PPH infusion', dose: '10 IU in 500 mL crystalloid at 125 mL/h', route: 'IV infusion', frequency: 'Continuous' },
      { indication: 'Augmentation', dose: 'Start 1-2 mIU/min titrate q30min to adequate contractions (max ~12-20 mIU/min per protocol)', route: 'IV pump', frequency: 'Titrated' },
    ],
    contraindications: ['Hypersensitivity', 'Caution grandmultipara/prior scar during induction'],
    adverseEffects: ['Water intoxication (prolonged high-dose), hypotension (rapid push), tachysystole'],
    monitoring: ['CTG once running', 'Fluid balance prolonged courses'],
    sourceId: 'who-uterotonics-2018', emergencyKit: true, status: P,
  },
  {
    id: 'carboprost', name: 'Carboprost (PGF2alpha)', drugClass: 'Uterotonic', dbCategory: 'uterotonics',
    indications: ['Refractory atonic PPH second-line uterotonic'],
    pregnancySafety: 'Therapeutic use only', lactation: 'Short-course compatible',
    doseRows: [{ indication: 'Atonic PPH', dose: '250 mcg IM q15 min up to 8 doses', route: 'IM', frequency: 'q15 min', max: '2 mg total (8 doses)' }],
    contraindications: ['Asthma (bronchospasm)', 'Cardiac/renal/hepatic severe disease caution'],
    adverseEffects: ['Bronchospasm, vomiting, diarrhoea, flushing, hypertension transient'],
    monitoring: ['Respiratory status esp. asthmatics'],
    sourceId: 'who-pph-consolidated-2025', emergencyKit: true, status: P,
  },
  {
    id: 'misoprostol', name: 'Misoprostol', drugClass: 'Prostaglandin E1 analogue', dbCategory: 'uterotonics',
    indications: ['PPH rescue where injectables unavailable', 'Medical abortion/miscarriage management', 'IOL (resource settings)'],
    pregnancySafety: 'Teratogenic reports with failed first-trimester exposure - counselling; therapeutic uses standardised by WHO/MTP guidance', lactation: 'Compatible',
    doseRows: [
      { indication: 'PPH rescue', dose: '800 mcg sublingual single', route: 'SL', frequency: 'Once' },
      { indication: 'MMA <=9-12 wks', dose: '800 mcg PV/SL after mifepristone priming; repeat 400 mcg q3h PRN', route: 'PV/SL/PO', frequency: 'Per protocol' },
      { indication: 'IOL unscarred', dose: '25 mcg PV/SL q2h max 8 doses', route: 'PV/SL', frequency: 'q2h' },
    ],
    adverseEffects: ['Pyrexia/shivering (antipyretics help), GI upset'],
    contraindications: ['Previous caesarean for IOL use'],
    sourceId: 'india-mtp-act-rules-2021', emergencyKit: true, status: P,
  },
  {
    id: 'ergometrine', name: 'Ergometrine / Methylergometrine', drugClass: 'Ergot alkaloid uterotonic', dbCategory: 'uterotonics',
    indications: ['Second-line PPH', 'Prophylaxis where oxytocin unavailable (no HTN)'],
    pregnancySafety: 'Post-BIRTH only (never before delivery - fetal effects)', lactation: 'Short courses OK; may suppress milk at high/prolonged doses',
    doseRows: [{ indication: 'PPH', dose: '0.5 mg IM (repeat 15-min intervals max 4) or 0.25-0.5 mg IV slow', route: 'IM/IV', frequency: 'Per response', max: '1 mg acute course' }],
    contraindications: ['Hypertension/pre-eclampsia', 'Cardiac/PVD disease', 'BEFORE birth of baby'],
    adverseEffects: ['Hypertensive crisis in PET, nausea, coronary spasm rare'],
    sourceId: 'who-pph-consolidated-2025', emergencyKit: true, status: P,
  },
  {
    id: 'labetalol', name: 'Labetalol', drugClass: 'Alpha-beta blocker antihypertensive', dbCategory: 'antihypertensives',
    indications: ['Chronic/GHTN/PE oral therapy', 'Acute severe hypertension IV'],
    pregnancySafety: 'First-line across guidelines', lactation: 'Compatible (low milk transfer)',
    doseRows: [
      { indication: 'Oral chronic therapy', dose: '100 mg BD titrate to 200-400 BD-TDS', route: 'PO', frequency: 'BD-TDS', max: '2400 mg/day' },
      { indication: 'IV acute', dose: '20 mg -> 40 -> 80 q10min prn', route: 'IV bolus', frequency: 'q10min', max: '300 mg cumulative' },
    ],
    contraindications: ['Asthma', 'Bradycardia/heart block', 'Heart failure'],
    adverseEffects: ['Bradycardia, hypotension, bronchospasm, neonatal hypoglycaemia late use'],
    monitoring: ['BP/HR during titration'],
    sourceId: 'isshp-2021', emergencyKit: true, status: P,
  },
  {
    id: 'nifedipine', name: 'Nifedipine', drugClass: 'Calcium channel blocker', dbCategory: 'antihypertensives',
    indications: ['Oral HDP therapy', 'Acute BP oral option', 'Tocolysis'],
    pregnancySafety: 'First-line; most studied CCB', lactation: 'Compatible (may reduce supply at high doses)',
    doseRows: [
      { indication: 'Maintenance HDP', dose: 'ER/Oros 10-20 mg OD-BD titrated', route: 'PO', frequency: 'OD-BD', max: '120 mg/day ER' },
      { indication: 'Acute severe', dose: '10 mg capsule PO repeat 20 min if needed then q4-6h bridge', route: 'PO', frequency: 'q20min x2-3 then maintenance' },
      { indication: 'Tocolysis', dose: '20 mg load then 10-20 q6-8h up to 48 h', route: 'PO', frequency: 'q6-8h', duration: '<=48 h' },
    ],
    contraindications: ['Concurrent MgSO4 vigilance', 'Aortic stenosis severe', 'Maternal hypotension'],
    adverseEffects: ['Headache/flushing/tachycardia; additive weakness with MgSO4'],
    sourceId: 'isshp-2021', emergencyKit: true, status: P,
  },
  {
    id: 'hydralazine', name: 'Hydralazine', drugClass: 'Direct vasodilator', dbCategory: 'antihypertensives',
    indications: ['Acute severe hypertension IV alternative'],
    pregnancySafety: 'Established obstetric use', lactation: 'Compatible',
    doseRows: [{ indication: 'Acute', dose: '5 mg IV slow q20 min prn', route: 'IV', frequency: 'q20min', max: '20 mg cumulative' }],
    contraindications: ['SLE/lupus-like history caution', 'CAD severe', 'Avoid precipitous drops'],
    adverseEffects: ['Reflex tachycardia/headache/fluid retention'],
    monitoring: ['BP q15 min after dosing'],
    sourceId: 'isshp-2021', emergencyKit: true, status: P,
  },
  {
    id: 'methyldopa', name: 'Methyldopa', drugClass: 'Central alpha-2 agonist', dbCategory: 'antihypertensives',
    indications: ['Oral HDP therapy (second preference)'],
    pregnancySafety: 'Long safety record', lactation: 'Compatible short-term; depression risk limits postpartum use',
    doseRows: [{ indication: 'Oral', dose: '250 mg BD-TDS titrate to max 500 mg QDS', route: 'PO', frequency: 'BD-QDS', max: '3 g/day' }],
    contraindications: ['Depression history', 'Liver disease', 'MAOI use'],
    adverseEffects: ['Sedation, dry mouth, depression, hepatitis (rare)'],
    monitoring: ['Coombs positivity expected; LFTs prolonged use', 'Stop within days postpartum typically'],
    sourceId: 'fogsi-hdp-gcpr-2026', status: P,
  },
  {
    id: 'aspirin-lowdose', name: 'Aspirin (low-dose)', drugClass: 'Antiplatelet', dbCategory: 'prevention',
    indications: ['Pre-eclampsia prevention high-risk', 'APS obstetric regimen'],
    pregnancySafety: 'Safe at low dose in pregnancy', lactation: 'Compatible',
    doseRows: [{ indication: 'PE prevention', dose: '75-150 mg nocte from 11-16 wks to 36 wks', route: 'PO', frequency: 'Nightly', duration: '~24 wks' }, { indication: 'APS obstetric', dose: '75-100 mg OD + LMWH', route: 'PO', frequency: 'Daily' }],
    contraindications: ['Active peptic ulcer', 'Aspirin allergy/bleeding diathesis'],
    sourceId: 'isshp-2021', status: P,
  },
  {
    id: 'enoxaparin', name: 'Enoxaparin (LMWH)', drugClass: 'Low molecular weight heparin', dbCategory: 'anticoagulants',
    indications: ['VTE treatment/prophylaxis', 'APS regimens'],
    pregnancySafety: 'Preferred anticoagulant in pregnancy', lactation: 'Compatible',
    doseRows: [
      { indication: 'Treatment', dose: '1 mg/kg SC q12h', route: 'SC', frequency: 'q12h', duration: 'At least 6 weeks postpartum (total >=3 months)' },
      { indication: 'Prophylaxis', dose: '40 mg SC daily (weight-adjust extremes)', route: 'SC', frequency: 'Daily' },
    ],
    contraindications: ['Active major bleeding', 'HIT history'],
    interactions: ['Neuraxial timing rules: stop 12 h pre-block (prophylactic) / 24 h (therapeutic); restart >=4 h after block/catheter removal'],
    monitoring: ['Anti-Xa peak in weight extremes/renal disease', 'Platelet baseline'],
    renalHepatic: 'CrCl<30 specialist advice',
    sourceId: 'rcog-gtg36-gbs-2017', emergencyKit: true, status: P,
  },
  {
    id: 'metformin', name: 'Metformin', drugClass: 'Biguanide', dbCategory: 'endocrine-metabolic',
    indications: ['GDM second-step', 'PCOS metabolic/OI adjunct', 'T2DM pregnancy continuation'],
    pregnancySafety: 'Safe; crosses placenta (follow-up reassuring)', lactation: 'Compatible',
    doseRows: [{ indication: 'General', dose: '500 mg OD titrate to 1000 mg BD (max 2000-2550/day)', route: 'PO', frequency: 'OD-BD-TDS with meals' }],
    contraindications: ['eGFR<30', 'Acute illness with hypoxia risk context'],
    adverseEffects: ['GI upset (titration), B12 deficiency long-term'],
    monitoring: ['Renal function annually', 'CBG targets'],
    sourceId: 'who-anc-2016-updates', status: P,
  },
  {
    id: 'insulin-nph', name: 'Insulin (NPH + rapid analogues)', drugClass: 'Endocrine replacement', dbCategory: 'endocrine-metabolic',
    indications: ['GDM third-step', 'Pregestational DM'],
    pregnancySafety: 'Gold standard glycaemic control in pregnancy', lactation: 'Compatible',
    doseRows: [{ indication: 'GDM start', dose: '~0.3 U/kg/day split basal-prandial; titrate pattern q3 days', route: 'SC', frequency: 'Basal+meals' }],
    contraindications: ['Hypoglycaemia episode active'],
    monitoring: ['SMBG/CGM', 'Hypo education'],
    sourceId: 'who-anc-2016-updates', emergencyKit: true, status: P,
  },
  {
    id: 'betamethasone', name: 'Betamethasone', drugClass: 'Corticosteroid', dbCategory: 'corticosteroids',
    indications: ['Antenatal lung maturity <34(+/-35+6) wks'],
    pregnancySafety: 'Benefit-proven; hyperglycaemia plan in diabetes', lactation: 'Compatible',
    doseRows: [{ indication: 'Standard course', dose: '12 mg IM x2 doses 24 h apart', route: 'IM', frequency: 'Two doses', duration: 'Single course/rescue rules' }],
    contraindications: ['Systemic infection weighing urgency'],
    monitoring: ['Glucose in diabetics q4-6h after doses'],
    sourceId: 'rcog-gtg74-steroids-2022', status: P,
  },
  {
    id: 'dexamethasone-anc', name: 'Dexamethasone (antenatal alternative)', drugClass: 'Corticosteroid', dbCategory: 'corticosteroids',
    indications: ['Where betamethasone unavailable'],
    pregnancySafety: 'Accepted equivalent', lactation: 'Compatible',
    doseRows: [{ indication: 'Course', dose: '6 mg IM/IV q12h x4 doses', route: 'IM/IV', frequency: 'q12h x4' }],
    sourceId: 'rcog-gtg74-steroids-2022', status: P,
  },
  {
    id: 'cefazolin', name: 'Cefazolin', drugClass: 'First-generation cephalosporin', dbCategory: 'antibiotics',
    indications: ['CS surgical prophylaxis', 'Other clean-contaminated prophylaxis'],
    pregnancySafety: 'Safe', lactation: 'Compatible',
    doseRows: [{ indication: 'CS prophylaxis', dose: '2 g IV within 60 min pre-incision (3 g >120 kg)', route: 'IV', frequency: 'Single dose', preparation: 'Push over 3-5 min' }],
    contraindications: ['Beta-lactam anaphylaxis -> clindamycin'],
    sourceId: 'nice-ng235-intrapartum-2026', status: P,
  },
  {
    id: 'ampicillin', name: 'Ampicillin', drugClass: 'Aminopenicillin', dbCategory: 'antibiotics',
    indications: ['Chorioamnionitis/endometritis component', 'GBS IAP alternative'],
    pregnancySafety: 'Safe', lactation: 'Compatible',
    doseRows: [
      { indication: 'Chorio', dose: '2 g IV q6h', route: 'IV', frequency: 'q6h', duration: 'Until birth (+post-CS course)' },
      { indication: 'GBS IAP', dose: '5 g load then 2.5 g q4h', route: 'IV', frequency: 'q4h' },
    ],
    contraindications: ['Penicillin anaphylaxis'],
    sourceId: 'cdc-sti-2021', emergencyKit: true, status: P,
  },
  {
    id: 'gentamicin', name: 'Gentamicin', drugClass: 'Aminoglycoside', dbCategory: 'antibiotics',
    indications: ['Chorio/endometritis/pyelo combination partner', 'Severe sepsis empiric'],
    pregnancySafety: 'Use when indicated (standard); fetal ototoxicity theoretical at prolonged high levels - keep courses short', lactation: 'Compatible',
    doseRows: [{ indication: 'Once-daily', dose: '5 mg/kg q24h IV (adjust levels/renal)', route: 'IV', frequency: 'q24h', duration: '48-72 h typical combination' }],
    contraindications: ['Myasthenia gravis caution', 'Prior ototoxicity'],
    monitoring: ['Levels/trough where available', 'Creatinine trend'],
    renalHepatic: 'Major renal adjustment',
    sourceId: 'cdc-sti-2021', status: P,
  },
  {
    id: 'ceftriaxone', name: 'Ceftriaxone', drugClass: 'Third-gen cephalosporin', dbCategory: 'antibiotics',
    indications: ['Gonorrhoea', 'PID outpatient anchor', 'Pyelonephritis', 'Sepsis empiric'],
    pregnancySafety: 'Safe', lactation: 'Compatible',
    doseRows: [
      { indication: 'Gonorrhoea', dose: '500 mg IM single (1 g >=150 kg)', route: 'IM', frequency: 'Once' },
      { indication: 'PID anchor', dose: '500 mg IM x1 (outpatient) or 1 g IV daily inpatient', route: 'IM/IV' },
      { indication: 'Pyelonephritis', dose: '1 g IV daily', route: 'IV', frequency: 'Daily' },
    ],
    contraindications: ['Cephalosporin anaphylaxis'],
    sourceId: 'cdc-sti-2021', emergencyKit: true, status: P,
  },
  {
    id: 'doxycycline', name: 'Doxycycline', drugClass: 'Tetracycline', dbCategory: 'antibiotics',
    indications: ['Chlamydia/PID NON-PREGNANT'],
    pregnancySafety: 'CONTRAINDICATED in pregnancy (teeth/bone) - azithromycin instead', lactation: 'Short courses acceptable but alternatives preferred',
    doseRows: [{ indication: 'PID/chlamydia non-pregnant', dose: '100 mg BD', route: 'PO', frequency: 'BD', duration: '7-14 d per syndrome' }],
    sourceId: 'cdc-sti-2021', status: P,
  },
  {
    id: 'metronidazole', name: 'Metronidazole', drugClass: 'Nitroimidazole', dbCategory: 'antibiotics',
    indications: ['BV', 'Trichomonas', 'Anaerobic cover chorio/endometritis/PID/sepsis'],
    pregnancySafety: 'Safe (meta-analytic reassurance); T1 use case-by-case symptomatic BV', lactation: 'Compatible (single high doses -> brief pause convention)',
    doseRows: [
      { indication: 'BV', dose: '400 mg BD x5 d', route: 'PO', frequency: 'BD' },
      { indication: 'Trichomonas pregnancy', dose: '400-500 mg BD x7 d', route: 'PO', frequency: 'BD' },
      { indication: 'IV anaerobic', dose: '500 mg IV q8h', route: 'IV', frequency: 'q8h' },
    ],
    contraindications: ['Alcohol abstinence during + 24 h', 'Disulfiram'],
    sourceId: 'cdc-sti-2021', status: P,
  },
  {
    id: 'azithromycin', name: 'Azithromycin', drugClass: 'Macrolide', dbCategory: 'antibiotics',
    indications: ['Chlamydia in pregnancy', 'Alternative MAC contexts'],
    pregnancySafety: 'Safe', lactation: 'Compatible',
    doseRows: [{ indication: 'Chlamydia', dose: '1 g PO single', route: 'PO', frequency: 'Once' }],
    sourceId: 'cdc-sti-2021', status: P,
  },
  {
    id: 'erythromycin-latency', name: 'Erythromycin (latency PPROM)', drugClass: 'Macrolide', dbCategory: 'antibiotics',
    indications: ['PPROM latency antibiotics'],
    pregnancySafety: 'GTG73 regimen', lactation: 'Compatible',
    doseRows: [{ indication: 'PPROM', dose: '250 mg QDS x10 days', route: 'PO', frequency: 'QDS', duration: '10 days max' }],
    sourceId: 'rcog-gtg73-pprom-2019', status: P,
  },
  {
    id: 'methotrexate-ectopic', name: 'Methotrexate (ectopic protocol)', drugClass: 'Antimetabolite', dbCategory: 'fertility-oncology',
    indications: ['Unruptured ectopic medical management'],
    pregnancySafety: 'INTENDED abortive/teratogenic here - strict eligibility', lactation: 'Contraindicated during course',
    doseRows: [{ indication: 'Single-dose protocol', dose: '50 mg/m2 BSA IM day 1; hCG d4/d7; second dose day 7 if criteria fail', route: 'IM', frequency: 'Protocol-driven', max: 'Two doses then surgery' }],
    contraindications: ['Rupture/instability', 'Moderate-severe pain', 'Heartbeat (relative)', '>3.5 cm', 'hCG>5000 relative', 'Blood dyscrasia/liver/kidney disease', 'Breastfeeding', 'No-follow-up patients'],
    monitoring: ['CBC/LFT/RFT baseline+d7', 'Weekly hCG to negative', 'NO NSAIDs/folate antagonism; no conception 3 months'],
    sourceId: 'rcog-gtg73-pprom-2019', status: P,
  },
  {
    id: 'mifepristone', name: 'Mifepristone', drugClass: 'Progesterone receptor antagonist', dbCategory: 'abortion-care',
    indications: ['Medical abortion priming (with misoprostol)', 'Miscarriage missed-management'],
    pregnancySafety: 'Intended use under MTP Act framework', lactation: 'Brief pause convention after dose',
    doseRows: [{ indication: 'MMA', dose: '200 mg PO, followed by misoprostol 24-48 h later', route: 'PO', frequency: 'Once' }],
    contraindications: ['Confirmed/suspected ectopic', 'Unmanaged adrenal/anticoagulation issues', 'Chronic adrenal failure'],
    sourceId: 'india-mtp-act-rules-2021', status: P,
  },
  {
    id: 'ondansetron', name: 'Ondansetron', drugClass: '5-HT3 antagonist', dbCategory: 'antiemetics',
    indications: ['Hyperemesis ladder', 'Perioperative antiemesis'],
    pregnancySafety: 'Large data reassuring; minimal absolute-risk discussions documented', lactation: 'Compatible',
    doseRows: [{ indication: 'HG', dose: '4-8 mg q8h PO/IV', route: 'PO/IV', frequency: 'q8h', max: '16 mg per dose IV push slowly (QTc)' }],
    monitoring: ['ECG awareness prolonged QT combinations'],
    sourceId: 'who-anc-2016-updates', status: P,
  },
  {
    id: 'pyridoxine-doxylamine', name: 'Pyridoxine ± doxylamine', drugClass: 'Antiemetic first-line NVP', dbCategory: 'antiemetics',
    indications: ['Nausea/vomiting of pregnancy first-line'],
    pregnancySafety: 'Best-established first-line', lactation: 'Compatible',
    doseRows: [{ indication: 'NVP/HG base', dose: 'Pyridoxine 10-25 mg TDS (+ doxylamine 12.5-25 mg nocte)', route: 'PO', frequency: 'TDS/nocte' }],
    sourceId: 'who-anc-2016-updates', status: P,
  },
  {
    id: 'thiamine', name: 'Thiamine', drugClass: 'Vitamin B1', dbCategory: 'vitamins',
    indications: ['HG prevention of Wernicke BEFORE dextrose fluids'],
    pregnancySafety: 'Essential', lactation: 'Compatible',
    doseRows: [{ indication: 'HG IV phase', dose: '100 mg IV slow daily while vomiting persists', route: 'IV/PO', frequency: 'Daily', preparation: 'Give BEFORE glucose-containing infusions' }],
    sourceId: 'who-anc-2016-updates', emergencyKit: true, status: P,
  },
  {
    id: 'iron-fcm', name: 'Iron (ferric carboxymaltose class)', drugClass: 'IV iron complex', dbCategory: 'haematology-adjuncts',
    indications: ['IDA intolerance/severe/late pregnancy'],
    pregnancySafety: 'T1 avoidance convention (data evolving); strong T2/T3 evidence', lactation: 'Compatible',
    doseRows: [{ indication: 'Deficit correction', dose: 'Weight-based deficit calculation (simplified: 1000 mg typical course; label maxima apply)', route: 'IV infusion', frequency: 'Single/repeated sessions', preparation: 'Observe 30 min post-infusion' }],
    contraindications: ['Active infection defer', 'Known hypersensitivity'],
    monitoring: ['Hb at 2-4 wks', 'Phosphate symptoms (FCM repeated courses)'],
    sourceId: 'who-anc-2016-updates', status: P,
  },
  {
    id: 'levonorgestrel-ecp', name: 'Levonorgestrel ECP', drugClass: 'Progestogen EC', dbCategory: 'contraceptives',
    indications: ['Emergency contraception <=72 h'],
    pregnancySafety: 'No effect on established pregnancy', lactation: 'Compatible',
    doseRows: [{ indication: 'Standard', dose: '1.5 mg PO single ASAP', route: 'PO', frequency: 'Once', notes: ['Repeat if vomit <3 h'] }],
    sourceId: 'cdc-sti-2021', status: P,
  },
  {
    id: 'calcium-gluconate', name: 'Calcium gluconate 10%', drugClass: 'Electrolyte antidote', dbCategory: 'emergency-drugs',
    indications: ['Magnesium toxicity reversal'],
    pregnancySafety: 'Life-saving antidote', lactation: 'n/a',
    doseRows: [{ indication: 'MgSO4 toxicity', dose: '10 mL IV over 3 minutes', route: 'IV', frequency: 'Repeat per toxicity course', preparation: 'Central/peripheral large vein' }],
    sourceId: 'fogsi-hdp-gcpr-2026', emergencyKit: true, status: P,
  },
]
