import type { EmergencyProtocol } from './types'

/* ============================================================
   EMERGENCY HUB (§54) — RECOGNIZE -> CALL -> ACT -> INVESTIGATE
   -> DEFINITIVE -> ESCALATE -> POST-EVENT
   ============================================================ */

const P = 'published' as const
function e(p: Partial<EmergencyProtocol> & Pick<EmergencyProtocol, 'id' | 'title' | 'group' | 'keywords' | 'recognize' | 'callForHelp' | 'immediateAction' | 'investigations' | 'definitiveManagement' | 'escalation' | 'postEventCare' | 'sourceIds'>): EmergencyProtocol {
  return { tone: 'critical', status: P, lastVerifiedAt: '2026-08-23', ...p } as EmergencyProtocol
}

export const EMERGENCIES: EmergencyProtocol[] = [
  e({
    id: 'emg-pph', title: 'Postpartum Haemorrhage', group: 'Haemorrhage', keywords: ['pph', 'bleeding after delivery', 'atony'],
    topicRef: 'pph',
    recognize: ['EBL >500 mL vaginal / >1000 mL CS or any haemodynamic compromise', 'Shock index >=0.9', 'Boggy uterus / continued ooze with firm uterus'],
    callForHelp: ['Declare "PPH" + note time', 'Senior obstetrician + anaesthetist', 'Blood bank alerted; MTP if major'],
    immediateAction: [{ kind: 'steps', steps: ['Two 16G IVs; bloods+crossmatch', 'Massage uterus; catheterise', 'Oxytocin 10 IU + infusion', 'TXA 1 g IV over 10 min within 3 h window', 'Quantify loss; warm fluids'] }],
    investigations: ['CBC, coags incl. fibrinogen, crossmatch, lactate'],
    definitiveManagement: [{ kind: 'steps', steps: ['4Ts exam: Tone/Trauma/Tissue/Thrombin', '2nd uterotonic (ergometrine/carboprost/misoprostol)', 'Balloon tamponade', 'Laparotomy ladder -> hysterectomy decision'] }],
    escalation: ['HDU/ICU after >4 units/coagulopathy/oliguria', 'NASG + tamponade before transfer in peripheral settings'],
    postEventCare: ['Serial Hb/coags', 'Iron replacement', 'VTE reassessment AFTER haemostasis', 'Debrief + documentation'],
    sourceIds: ['who-pph-consolidated-2025', 'who-txa-pph-2017'],
  }),
  e({
    id: 'emg-eclampsia', title: 'Eclampsia', group: 'Hypertensive', keywords: ['fits', 'seizure pregnancy', 'convulsions'],
    topicRef: 'hdp-eclampsia',
    recognize: ['Generalised seizure in hypertensive pregnant/postpartum woman'],
    callForHelp: ['Senior obstetrician + anaesthetist immediately', 'Note time'],
    immediateAction: [{ kind: 'steps', steps: ['Left lateral; protect injury; suction ready', 'O2 15 L/min non-rebreather', 'MgSO4 Pritchard LOADING NOW: 4 g IV slow + 5 g IM x2 buttocks', 'BP >=160/110 -> labetalol/hydralazine/nifedipine'] }],
    investigations: ['CBC, platelets, coags, creatinine, LFTs; CT only if atypical'],
    definitiveManagement: [{ kind: 'list', items: ['Maintenance MgSO4 5 g IM q4h (24 h after last seizure/delivery)', 'Deliver once STABILISED (>=34 wks now; <34 individualised)', 'Recurrence: MgSO4 2 g IV after toxicity check'] }],
    escalation: ['ICU for recurrent seizures/ventilation/coma'],
    postEventCare: ['Toxicity monitoring each dose', 'Neonatal hypermagnesaemia alert', 'Postnatal BP/labs surveillance'],
    sourceIds: ['fogsi-hdp-gcpr-2026', 'isshp-2021'],
  }),
  e({
    id: 'emg-severe-htn', title: 'Acute Severe Hypertension (>=160/110)', group: 'Hypertensive', keywords: ['high bp emergency', 'severe hypertension'],
    topicRef: 'hdp-severe-features',
    recognize: ['SBP>=160 and/or DBP>=110 confirmed within 15 min'],
    callForHelp: ['Obstetric senior review same minutes'],
    immediateAction: [{ kind: 'list', items: ['Labetalol IV 20->40->80 mg q10min OR hydralazine 5 mg q20min OR nifedipine 10 mg PO repeat', 'Target SBP 130-150/DBP 80-90 (no precipitous drops)'] }],
    investigations: ['Platelets/LFTs/creatinine/coags; CTG'],
    definitiveManagement: [{ kind: 'list', items: ['Transition to oral maintenance agents', 'Delivery timing per underlying disorder'] }],
    escalation: ['HDU during acute control'],
    postEventCare: ['q15-20 min BP x1 h then hourly', 'Document agent sequence'],
    sourceIds: ['isshp-2021', 'fogsi-hdp-gcpr-2026'],
  }),
  e({
    id: 'emg-maternal-collapse', title: 'Maternal Collapse / Cardiac Arrest', group: 'Collapse', keywords: ['collapse', 'arrest', 'cpr pregnant'],
    recognize: ['Unresponsive/apnoeic/pulseless pregnant or postpartum woman'],
    callForHelp: ['Code blue + obstetrician + anaesthetist + neonatal team'],
    immediateAction: [{ kind: 'steps', steps: ['CPR per ACLS with manual uterine displacement LEFT', 'Defibrillation energies unchanged', 'PERIMORTEM CAESAREAN at 4 min if >=20 wks (aim birth <5 min)', 'Reversible causes: haemorrhage, AFE, PE, eclampsia, sepsis, drug toxicity'] }],
    investigations: ['During CPR: ABG/glucose/K; ultrasound FAST'],
    definitiveManagement: [{ kind: 'text', text: 'Treat identified cause simultaneously (MTP for haemorrhage; thrombolysis for massive PE where no surgery).' }],
    escalation: ['ICU post-return-of-circulation'],
    postEventCare: ['Debrief; documentation; neonatal pathway'],
    sourceIds: ['who-pph-consolidated-2025'],
  }),
  e({
    id: 'emg-sepsis', title: 'Maternal Sepsis', group: 'Infection', keywords: ['fever postpartum', 'sepsis', 'rigors'],
    topicRef: 'maternal-sepsis',
    recognize: ['Fever >38/<36, HR>110, RR>25, SBP<90, SpO2<94%, confusion'],
    callForHelp: ['Declare sepsis; senior review'],
    immediateAction: [{ kind: 'steps', steps: ['Cultures+lactate BEFORE antibiotics (never delaying them)', 'Broad-spectrum IV antibiotics within 1 h', 'Crystalloid 30 mL/kg (individualise PET/cardiac)', 'Hourly urine output catheter'] }],
    investigations: ['Lactate, cultures, CBC/U&E/LFT/coags, US for source'],
    definitiveManagement: [{ kind: 'text', text: 'SOURCE CONTROL: evacuate RPOC, drain collections, debride wounds, deliver infected uterus when indicated.' }],
    escalation: ['ICU vasopressors/ventilation/dialysis'],
    postEventCare: ['48-72 h antibiotic review', 'AKI/DIC surveillance'],
    sourceIds: ['rcog-gtg36-gbs-2017'],
  }),
  e({
    id: 'emg-shoulder-dystocia', title: 'Shoulder Dystocia', group: 'Birth emergency', keywords: ['turtle sign', 'shoulder stuck'],
    topicRef: 'shoulder-dystocia',
    recognize: ['Head delivers then retracts (turtle sign); axial traction fails'],
    callForHelp: ['Declare dystocia + time; neonatal team + anaesthetist'],
    immediateAction: [{ kind: 'steps', steps: ['STOP pushing/oxytocin; NO fundal pressure', 'McRoberts + suprapubic pressure', 'Internal rotation Rubin/Woods', 'Posterior arm delivery', 'All-fours repeat', 'Rescue: cleidotomy/Zavanelli/symphysiotomy'] }],
    investigations: ['None - act'],
    definitiveManagement: [{ kind: 'text', text: 'Birth -> cord gases, PPH bundle, genital tract exam incl. rectum.' }],
    escalation: ['NICU for asphyxia risk'],
    postEventCare: ['Brachial plexus exam newborn', 'Documentation of times/manoeuvres', 'Parent debrief'],
    sourceIds: ['nice-ng235-intrapartum-2026'],
  }),
  e({
    id: 'emg-cord-prolapse', title: 'Cord Prolapse', group: 'Birth emergency', keywords: ['cord visible', 'bradycardia after ROM'],
    topicRef: 'cord-prolapse',
    recognize: ['Cord seen/palpated beside presenting part after ROM; sudden prolonged bradycardia'],
    callForHelp: ['Declare + time'],
    immediateAction: [{ kind: 'steps', steps: ['Manual elevation of presenting part OFF cord (keep hand)', 'Knee-chest/exaggerated Sims position', 'Fill bladder 500 mL saline', 'Category-1 caesarean unless vaginal imminent'] }],
    investigations: ['Continuous FHR until feasible'],
    definitiveManagement: [{ kind: 'text', text: 'Rapid birth; transport WITH relieving hand.' }],
    escalation: ['Neonatal resuscitation readiness'],
    postEventCare: ['Cord gases; cooling eligibility assessment; debrief'],
    sourceIds: ['nice-ng235-intrapartum-2026'],
  }),
  e({
    id: 'emg-eclampsia-postpartum-fit', title: 'Postpartum Seizure (non-eclamptic differentials)', group: 'Collapse', keywords: ['fit after delivery', 'postpartum seizure'],
    recognize: ['Seizure >48 h postpartum or without hypertension'],
    callForHelp: ['Senior + anaesthesia'],
    immediateAction: [{ kind: 'steps', steps: ['ABC; glucose check IMMEDIATELY', 'MgSO4 still given if any hypertension overlap', 'Diazepam/labetalol alternatives per cause', 'Imaging plan: CVT/PRES/ICH/ECLAMPSIA all live differentials'] }],
    investigations: ['Glucose, electrolytes, Mg, CT/MRV brain'],
    definitiveManagement: [{ kind: 'text', text: 'Cause-specific: anticoagulation CVT, BP control PRES, ASM loading epilepsy.' }],
    escalation: ['Neurology+ICU'],
    postEventCare: ['Airway protection until fully conscious'],
    sourceIds: ['fogsi-hdp-gcpr-2026'],
  }),
  e({
    id: 'emg-ectopic', title: 'Suspected Ruptured Ectopic', group: 'Early pregnancy', keywords: ['ectopic rupture', 'shoulder tip pain pregnancy'],
    topicRef: 'ectopic-pregnancy',
    recognize: ['Positive hCG + pain/bleeding + instability/faintness/shoulder tip'],
    callForHelp: ['Emergency theatre + anaesthetist + crossmatch'],
    immediateAction: [{ kind: 'steps', steps: ['Two large IVs; crystalloid+blood early (O-neg if immediate need)', 'Bedside US while resuscitating', 'Straight to theatre laparoscopy/laparotomy'] }],
    investigations: ['Crossmatch 4 units, CBC, Rh, quantitative hCG (never delaying surgery)'],
    definitiveManagement: [{ kind: 'text', text: 'Surgical control (salpingectomy usually); MTP if massive.' }],
    escalation: ['MTP activation; ICU if shock profound'],
    postEventCare: ['Anti-D Rh-negative; psychological support; STI screen offer'],
    sourceIds: ['rcog-gtg73-pprom-2019'],
  }),
  e({
    id: 'emg-aph-massive', title: 'Massive APH (praevia/abruption)', group: 'Haemorrhage', keywords: ['bleeding pregnancy third trimester'],
    topicRef: 'aph-previa',
    recognize: ['Any significant antepartum bleed', 'Pain+tense uterus (abruption)'],
    callForHelp: ['Senior + anaesthetist + blood bank + neonatal'],
    immediateAction: [{ kind: 'steps', steps: ['Left-lateral tilt; two IVs; crossmatch 4', 'NO digital exams until praevia excluded', 'CTG continuous', 'Steroids <34+6; MgSO4 <32 if birth imminent', 'Decision clock: birth vs stabilise-and-birth'] }],
    investigations: ['CBC, coags incl. fibrinogen, Kleihauer if Rh-, US localisation'],
    definitiveManagement: [{ kind: 'text', text: 'Caesarean for significant bleeding/major praevia/compromised fetus; vaginal route may suit stable abruption with fetal death.' }],
    escalation: ['MTP; HDU/ICU'],
    postEventCare: ['Coagulopathy watch', 'Rh prophylaxis', 'Histopathology placenta'],
    sourceIds: ['who-pph-consolidated-2025'],
  }),
  e({
    id: 'emg-pe', title: 'Massive Pulmonary Embolism', group: 'Vascular', keywords: ['pe collapse', 'chest pain breathless postpartum'],
    topicRef: 'vte',
    recognize: ['Collapse/hypoxia/tachycardia ± pleuritic pain; high clinical probability'],
    callForHelp: ['Anaesthetist + senior physician/obstetrician simultaneously'],
    immediateAction: [{ kind: 'steps', steps: ['High-flow O2; left-lateral tilt', 'LMWH therapeutic dose immediately pending imaging (stable cases imaging-first per protocol)', 'Arrest/unstable: consider THROMBOLYSIS without delay'] }],
    investigations: ['CXR/ECG/ABG; CTPA when stable enough'],
    definitiveManagement: [{ kind: 'text', text: 'Anticoagulation backbone; embolectomy/catheter options where thrombolysis contraindicated.' }],
    escalation: ['ICU; cardiothoracic liaison'],
    postEventCare: ['Extended LMWH >=6 wks postpartum; neuraxial timing chart'],
    sourceIds: ['rcog-gtg36-gbs-2017'],
  }),
  e({
    id: 'emg-massive-transfusion', title: 'Massive Transfusion Activation', group: 'Haemorrhage', keywords: ['mtp', 'blood products'],
    topicRef: 'pph',
    recognize: ['Bleeding with shock or predicted >4 units rapidly'],
    callForHelp: ['Activate MTP single-call protocol; transfusion specialist'],
    immediateAction: [{ kind: 'steps', steps: ['Ratio-based components ~1:1:1 PRBC:FFP:platelets', 'Tranexamic acid per PPH rules', 'Warm everything; calcium after every 4 units', 'Point-of-care coags/Hb loops'] }],
    investigations: ['Serial ABG/K/Ca; fibrinogen target >1.5-2 g/L'],
    definitiveManagement: [{ kind: 'text', text: 'Source control continues in parallel - products buy time, not cure.' }],
    escalation: ['ICU; interventional radiology availability check'],
    postEventCare: ['Citrate toxicity/hyperkalaemia watch', 'Transfusion reaction vigilance'],
    sourceIds: ['who-pph-consolidated-2025'],
  }),
  e({
    id: 'emg-uterine-inversion', title: 'Uterine Inversion', group: 'Birth emergency', keywords: ['fundus not palpable', 'inversion'],
    recognize: ['Fundus dimpled/absent + mass at introitus + shock out of proportion to loss'],
    callForHelp: ['Anaesthetist urgently (relaxation needed)'],
    immediateAction: [{ kind: 'steps', steps: ['Do NOT remove attached placenta', 'Immediate manual replacement (Johnson): push fundus through cervix toward umbilicus, hold 3-5 min', 'Halothane/nitroglycerin relaxation if needed', 'Hydrostatic methods alternative'] }],
    investigations: ['Crossmatch; treat shock aggressively'],
    definitiveManagement: [{ kind: 'text', text: 'Replacement -> oxytocin infusion to maintain tone; surgical (Haultain) rarely for failed replacement.' }],
    escalation: ['Theatre always'],
    postEventCare: ['PPH/DIC surveillance; debrief'],
    sourceIds: ['who-pph-consolidated-2025'],
  }),
  e({
    id: 'emg-afe', title: 'Amniotic Fluid Embolism', group: 'Collapse', keywords: ['afe', 'sudden collapse labour'],
    recognize: ['Abrupt hypoxia+hypotension+coagulopathy±seizure during labour/birth/early puerperium'],
    callForHelp: ['Full team activation; ICU'],
    immediateAction: [{ kind: 'steps', steps: ['Oxygenation±ventilation', 'Aggressive coagulopathy management EARLY (unlike other arrests)', 'Vasopressor support; avoid fluid overload', 'Perimortem caesarean rule applies if arrest'] }],
    investigations: ['Coags (DIC near-universal), ABG, crossmatch'],
    definitiveManagement: [{ kind: 'text', text: 'Supportive critical care; delivery expedited once maternal circulation addressed.' }],
    escalation: ['ICU mandatory; ECMO consideration centres'],
    postEventCare: ['Multisystem recovery; family communication lead'],
    sourceIds: ['who-pph-consolidated-2025'],
  }),
  e({
    id: 'emg-anaphylaxis', title: 'Anaphylaxis in Pregnancy', group: 'Allergy', keywords: ['allergic reaction', 'anaphylaxis'],
    recognize: ['Acute urticaria/stridor/wheeze/hypotension after drug/food/latex exposure'],
    callForHelp: ['Anaesthetist'],
    immediateAction: [{ kind: 'steps', steps: ['ADRENALINE 0.5 mg IM (0.5 mL 1:1000) anterolateral thigh; repeat 5-min intervals', 'Left-lateral tilt; O2; rapid crystalloid', 'Stop suspected agent; chlorphenamine+hydrocortisone secondary'] }],
    investigations: ['Mast tryptase sample (later), obs'],
    definitiveManagement: [{ kind: 'text', text: 'Adrenaline titration; biphasic observation 6-12 h; obstetric monitoring (fetal distress from maternal hypotension resolves with restoration).' }],
    escalation: ['HDU if refractory'],
    postEventCare: ['Allergy documentation/referral'],
    sourceIds: ['who-anc-2016-updates'],
  }),
  e({
    id: 'emg-hypo-hyperglycemia', title: 'Severe Hypo/Hyperglycaemia in Pregnancy', group: 'Metabolic', keywords: ['hypoglycaemia pregnancy', 'dka'],
    topicRef: 'pregestational-diabetes',
    recognize: ['Glucose <54 symptomatic OR DKA triad (ketones+acidosis+hyperglycaemia)'],
    callForHelp: ['Endocrinology/physician + senior obstetric'],
    immediateAction: [{ kind: 'steps', steps: ['HYPO: 50% dextrose 50 mL IV (or glucagon IM); recheck 15 min', 'DKA: isotonic fluids first litre fast + insulin infusion 0.1 U/kg/h (glucose may be normal-ish in pregnancy!) + potassium care'] }],
    investigations: ['Ketones (blood preferred), VBG, K+, corrected Na, anion gap hourly loops'],
    definitiveManagement: [{ kind: 'list', items: ['DKA resolution: ketones <0.6/anion-gap closure -> overlap subcutaneous insulin before stopping infusion', 'Continuous fetal monitoring viable gestations'] }],
    escalation: ['HDU/ICU for DKA'],
    postEventCare: ['Insulin regimen revision; sick-day education'],
    sourceIds: ['who-anc-2016-updates'],
  }),
  e({
    id: 'emg-torsion', title: 'Suspected Ovarian Torsion', group: 'Gynaecology', keywords: ['ovarian torsion', 'acute pelvic pain'],
    topicRef: 'adnexal-mass-torsion',
    recognize: ['Acute unilateral pelvic pain+vomiting; adnexal mass'],
    callForHelp: ['Emergency gynaecology review NOW'],
    immediateAction: [{ kind: 'steps', steps: ['Do NOT await Doppler confirmation', 'Prepare diagnostic laparoscopy'] }],
    investigations: ['US (supportive only), CBC/CRP differential'],
    definitiveManagement: [{ kind: 'text', text: 'Laparoscopic DETORSION of all viable ovaries; cystectomy per ischaemia; oophorectomy only non-viable/necrotic.' }],
    escalation: ['Theatre within hours'],
    postEventCare: ['Histology; fertility counselling'],
    sourceIds: ['cdc-sti-2021'],
  }),
  e({
    id: 'emg-uterine-rupture', title: 'Uterine Rupture', group: 'Birth emergency', keywords: ['scar dehiscence', 'rupture vbac'],
    topicRef: 'vbac-tolac',
    recognize: ['Abnormal CTG (commonest), loss of station, scar pain, haematuria, shock'],
    callForHelp: ['Cat-1 caesarean activation + anaesthetist + MTP primed'],
    immediateAction: [{ kind: 'steps', steps: ['Stop oxytocin; left-lateral', 'Two IVs + crossmatch running', 'Immediate laparotomy'] }],
    investigations: ['None delay surgery; labs parallel'],
    definitiveManagement: [{ kind: 'text', text: 'Repair vs hysterectomy intraoperatively; bladder check; massive haemorrhage readiness.' }],
    escalation: ['ICU; NICU coordination'],
    postEventCare: ['Cooling-eligible neonates pathway; debrief'],
    sourceIds: ['nice-ng235-intrapartum-2026'],
  }),
]
