import type { DiseaseTopic } from '../types'

/* ============================================================
   MEDICAL DISORDERS — Part B (VTE, sepsis, HG, ICP, chronic conditions)
   Sources: WHO PPH/TXA verified; sepsis per RCOG/WHO principles;
   CDC STI for syphilis dosing. Honest verification statuses.
   ============================================================ */

export const MEDICAL_TOPICS_B: DiseaseTopic[] = [
  {
    id: 'vte',
    title: 'VTE in Pregnancy (DVT/PE + Thromboprophylaxis)',
    category: 'obstetric-emergency',
    tags: ['vte', 'dvt', 'pe', 'lmwh', 'thromboprophylaxis'],
    aliases: ['blood clot', 'deep vein thrombosis', 'pulmonary embolism'],
    status: 'published',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'international-first',
    summary: 'Suspect PE -> LMWH immediately pending imaging in most stable patients. Weight-based enoxaparin. Neuraxial rules: prophylactic dose 12 h before/4 h after epidural-spinal (24h therapeutic). Continue >=6 wks postpartum; breastfeeding-compatible.',
    definition: 'DVT/PE antepartum or to 12 weeks postpartum.',
    redFlags: ['Haemodynamic instability suspected PE -> immediate thrombolysis decision', 'Iliac DVT (whole-leg swelling + back pain)', 'Post-CS breathlessness never dismissed as anaemia alone', 'Anticoagulated + bleeding = dual emergency'],
    differentials: [
      { condition: 'Normal pregnancy dyspnoea', clue: 'Gradual, no hypoxia' },
      { condition: 'Pneumonia', clue: 'Fever/focus' },
      { condition: 'Peripartum cardiomyopathy', clue: 'Echo dysfunction' },
      { condition: 'AFE', clue: 'Catastrophic intrapartum collapse' },
    ],
    initialAssessment: [{ kind: 'steps', steps: [
      'DVT suspicion: whole-leg duplex compression US same day',
      'PE suspicion: CXR -> ECG -> ABG; CTPA or V/Q (both pregnancy-safe; CTPA first-line many units)',
      'Start LMWH BEFORE imaging if clinical probability high and no bleeding contraindication',
      'Baseline CBC (platelets!), renal function, weight documented',
    ] }],
    investigations: [
      { test: 'Compression US leg', lookingFor: 'DVT confirmation' },
      { test: 'CTPA/V-Q', lookingFor: 'PE confirmation' },
      { test: 'D-dimer NOT useful in pregnancy', lookingFor: '-' },
      { test: 'Thrombophilia testing deferred 6+ wks post-treatment', lookingFor: 'Later workup only where management-changing' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'list', items: ['Massive PE with collapse: resuscitate + consider systemic thrombolysis (alteplase 100 mg over 2 h) - obstetric teams should not fear it; deliver decision individualised'] }],
      firstLine: [
        { kind: 'doseCard', drug: 'Enoxaparin (TREATMENT)', dose: '1 mg/kg SC q12h (or 1.5 mg/kg once daily)', route: 'SC', frequency: 'q12h', duration: 'Antepartum until birth then >=6 wks postpartum (min total 3 months)', monitoring: ['Anti-Xa peak (3-4 h post-dose) in extremes of weight/renal disease', 'Platelets baseline (HIT rare with LMWH)'], contraindications: ['Active major bleeding', 'Severe HIT history'], notes: ['Breastfeeding-compatible'], sourceId: 'rcog-gtg36-gbs-2017' },
        { kind: 'doseCard', drug: 'Enoxaparin (PROPHYLAXIS)', dose: '40 mg SC daily (intermediate 40 mg BD / higher weights adjusted)', route: 'SC', frequency: 'Daily', duration: 'Per risk assessment - typically from admission/CS day 1 through early postpartum (28-day extended courses for high risk)', notes: ['Timing vs neuraxial: stop 12 h pre-block; restart >=4 h after block/catheter removal (therapeutic doses: 24 h/6-12 h)'], sourceId: 'rcog-gtg36-gbs-2017' },
      ],
      alternativesFirstLine: [{ kind: 'list', items: ['Dalteparin/tinzaparin equivalents', 'Warfarin POSTPARTUM only (teratogenic) when longer therapy needed; breastfeeding-compatible'] }],
      drugTreatment: [],
      definitiveTreatment: [{ kind: 'text', text: 'Anticoagulation is definitive therapy; duration per event type/risk.' }],
      monitoring: [{ kind: 'table', headers: ['Domain', 'Rule'], rows: [
        ['Bleeding surveillance', 'PV loss quantified in labour plans'],
        ['Platelets', 'Baseline; periodic if extended course'],
        ['Renal function', 'CrCl <30 -> specialist dosing'],
        ['Neuraxial coordination', 'Anaesthetist-led timing chart at admission'],
      ] }],
      responseAssessment: [{ kind: 'list', items: ['Symptom resolution; no propagation on imaging where repeated'] }],
      treatmentFailure: [{ kind: 'list', items: ['Recurrent VTE on LMWH -> check adherence/dose (anti-Xa), switch BD regimen, haematology input'] }],
      secondLine: [{ kind: 'list', items: ['IV UFH peri-delivery windows where rapid reversal needed'] }],
      rescue: [{ kind: 'text', text: 'Massive PE: alteplase; catheter-directed/embolectomy where available; protamine reversal for UFH emergencies.' }],
      procedures: [{ kind: 'text', text: 'IVC filters rarely (contraindication to anticoagulation + recurrent PE).' }],
      escalation: [{ kind: 'list', items: ['ICU massive PE', 'Haematology co-management complex cases'] }],
      complications: [
        { name: 'Post-thrombotic syndrome', management: [{ kind: 'text', text: 'Compression stockings counselling' }] },
        { name: 'Anticoagulation near delivery', management: [{'kind':'text','text':'Planned induction timing lets last dose align with neuraxial windows'}] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['>=6 weeks postpartum minimum (3 months total typical)', 'Future-pregnancy prophylaxis plan documented', 'Thrombophilia panel deferred/reconsidered'] }],
    },
    sourceIds: ['rcog-gtg36-gbs-2017'],
    emergencyRef: 'emg-pe',
  },

  {
    id: 'maternal-sepsis',
    title: 'Maternal Sepsis',
    category: 'obstetric-emergency',
    tags: ['sepsis', 'chorioamnionitis', 'endometritis', 'antibiotics', 'lactate'],
    aliases: ['puerperal sepsis', 'postpartum fever', 'infection shock'],
    status: 'clinically-verified',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'india-first',
    summary: 'Pregnancy-specific triggers (septic abortion, chorioamnionitis, endometritis, mastitis necrosis, UTI/pyelo). Sepsis Six adapted: cultures+lactate, broad antibiotics within 1 h, fluids, oxygen as needed, source control (EVACUATE retained products!), hourly reassessment.',
    definition: 'Life-threatening organ dysfunction from infection in pregnancy/puerperium (qSOFA/news-style screening plus obstetric context).',
    redFlags: [
      'Temp >38 or <36 · HR>110 · RR>25 · SBP<90 · SpO2<94%',
      'Confusion/sluggishness post-birth ("just tired")',
      'Foul-smelling liquor/discharge + uterine tenderness',
      'Rigors + loin pain (pyelonephritis)',
      'Retained products + fever = surgical emergency combo',
    ],
    differentials: [
      { condition: 'Chorioamnionitis', clue: 'Intrapartum fever+foul liquor' },
      { condition: 'Endometritis', clue: 'Post-CS/post-evacuation uterine tenderness' },
      { condition: 'Septic abortion', clue: 'Unsafe-MTP context; retained products' },
      { condition: 'Pyelonephritis', clue: 'Loin pain+urine findings' },
      { condition: 'Necrotising fasciitis (perineal/wound)', clue: 'Pain out of proportion+skin changes' },
    ],
    initialAssessment: [
      { kind: 'steps', steps: [
        'RECOGNISE: obs-triggered screening each shift',
        'CALL senior + declare sepsis; note time',
        'SEPSIS SIX within the hour: O2 if hypoxic · IV access x2 + bloods incl. lactate+cultures · IV fluids 30 mL/kg crystalloid (caution PET/cardiac) · IV broad-spectrum antibiotics · catheter+hourly urine · reassess',
        'SOURCE hunt: PV exam, US for RPOC/collections, wound inspection',
      ] },
    ],
    investigations: [
      { test: 'Lactate', lookingFor: '>2 raised; >=4 high-risk' },
      { test: 'Blood cultures x2 BEFORE antibiotics (never delaying them)', lookingFor: 'Organism guidance' },
      { test: 'CBC, CRP, U&E, LFT, coags', lookingFor: 'Organ dysfunction/DIC' },
      { test: 'US pelvis', lookingFor: 'Retained products/collections driving source control' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'warning', title: 'Hour-1 bundle', text: 'Cultures+lactate drawn AND antibiotics running AND fluids started within 60 min of recognition.' }],
      investigations: [{ kind: 'text', text: 'Never delay antibiotics >45-60 min for results.' }],
      firstLine: [
        { kind: 'table', headers: ['Source', 'First-line empiric (adjust locally)'], rows: [
          ['Chorioamnionitis/endometritis', 'Ampicillin 2 g IV q6h + Gentamicin 5 mg/kg q24h (+ Metronidazole 500 mg IV q8h if post-op/septic abortion context)'],
          ['Alternative cephalosporin-based', 'Ceftriaxone 1 g IV q24h + Metronidazole 500 mg IV q8h'],
          ['Pyelonephritis', 'Ceftriaxone 1 g IV daily (de-escalate by culture)'],
          ['Septic abortion with RPOC', 'Above antibiotics + EVACUATION as source control'],
          ['Group A strep suspicion', 'Add clindamycin 900 mg q8h (toxin suppression) + urgent source control'],
        ] },
        { kind: 'doseCard', drug: 'Crystalloid resuscitation', dose: '30 mL/kg balanced solution initial (individualise: PET pulmonary oedema risk, cardiac disease)', route: 'IV', frequency: 'Bolus-assess loops', notes: ['Noradrenaline via central/large-bore when fluids exhausted; ICU transfer'], sourceId: 'rcog-gtg36-gbs-2017' },
      ],
      definitiveTreatment: [{ kind: 'list', items: ['SOURCE CONTROL IS DECISIVE: evacuate retained products, drain collections (US-guided), debride necrotic wounds', 'Deliver if intrauterine infection unresponsive (obstetric judgement)'] }],
      monitoring: [{ kind: 'table', headers: ['Parameter', 'Frequency until improving'], rows: [
        ['Obs/qSOFA elements', 'Hourly'],
        ['Urine output', 'Hourly (>0.5 mL/kg/h)'],
        ['Lactate repeat', 'At 2-4 h if initially raised'],
        ['Antibiotic review', '48-72 h culture-guided de-escalation'],
      ] }],
      responseAssessment: [{ kind: 'list', items: ['Lactate falling, vasopressor-free stability, afebrile trajectory, organ recovery'] }],
      treatmentFailure: [{ kind: 'list', items: [
        'Not improving at 6 h -> re-examine SOURCE (missed collection/RPOC/necrotising infection)',
        'Broaden cover; ICU escalation; imaging (CT)',
        'Consider DIC (coags) and AKI pathways',
      ] }],
      secondLine: [{ kind: 'list', items: ['Meropenem-class escalation per microbiology; antifungal consideration prolonged ICU'] }],
      rescue: [{ kind: 'text', text: 'Necrotising infection: emergency wide debridement theatre; toxic-shock physiology: clindamycin+immunoglobulin discussion.' }],
      procedures: [{ kind: 'text', text: 'MVA/EVAC under antibiotics COVER (not after "cure") when products retained.' }],
      escalation: [{ kind: 'list', items: ['HDU/ICU criteria: vasopressors, ventilation, dialysis', 'Peripheral centre: start bundle THEN transfer with escort'] }],
      complications: [
        { name: 'DIC', management: [{ kind: 'text', text: 'Component therapy; treat trigger' }] },
        { name: 'AKI', management: [{ kind: 'text', text: 'Fluid stewardship; dialysis indications' }] },
        { name: 'Sheehan (late pituitary insult)', management: [{ kind: 'text', text: 'Endocrine follow-up if prolonged shock' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['Complete antibiotic course per source; wound care', 'Debrief + documentation', 'Contraception/breastfeeding continuity planning'] }],
    },
    algorithm: [
      { id: 's1', label: 'Trigger criteria met', type: 'start', tone: 'danger' },
      { id: 's2', label: 'DECLARE SEPSIS · help called', type: 'action', tone: 'danger', next: [{ to: 's3' }] },
      { id: 's3', label: 'Sepsis Six hour-1 (cultures·lactate·abx·fluids·O2·catheter)', type: 'action', next: [{ to: 's4' }] },
      { id: 's4', label: 'SOURCE identified?', type: 'decision', next: [{ to: 's5', edgeLabel: 'YES' }, { to: 's6', edgeLabel: 'NO -> imaging/exam loop' }] },
      { id: 's5', label: 'CONTROL IT NOW (evacuate/drain/debride/deliver)', type: 'end', tone: 'danger' },
      { id: 's6', label: 'Reassess hourly; escalate ICU if not improving 6 h', type: 'end', tone: 'warn' },
    ],
    sourceIds: ['rcog-gtg36-gbs-2017'],
    emergencyRef: 'emg-sepsis',
  },

  {
    id: 'hyperemesis-gravidarum',
    title: 'Hyperemesis Gravidarum',
    category: 'medical-disorders',
    tags: ['hg', 'vomiting-pregnancy', 'thiamine', 'antiemetics'],
    status: 'published',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'india-first',
    summary: 'PUQE scoring guides severity. Rehydrate (thiamine BEFORE dextrose!), pyridoxine+doxylamine/pyridoxine monotherapy first line, add ondansetron/promethazine/metoclopramide ladder; steroids late-resort; thromboprophylaxis when immobile.',
    definition: 'Persistent vomiting >3x/day + >5% weight loss/ketonuria beyond simple NVP causing metabolic disturbance.',
    redFlags: ['Wernicke signs (confusion/ataxia/nystagmus) - thiamine deficiency', 'Severe electrolyte derangement', 'Intractable despite multi-agent', 'Weight loss >10%', 'Venous thrombosis signs'],
    initialAssessment: [{ kind: 'steps', steps: [
      'Exclude causes: multiple pregnancy/molar (scan), UTI, thyroid (can coexist), GI obstruction',
      'PUQE score; weight; mucous membranes; ketones (urine/blood)',
      'Bloods: U&E (K!, Na), LFT, urate, CBC, TFTs if indicated',
    ] }],
    investigations: [
      { test: 'U&E + magnesium/phosphate if severe', lookingFor: 'Hypokalaemia/hyponatraemia correction needs' },
      { test: 'Urine ketones', lookingFor: 'Starvation marker' },
      { test: 'TVS', lookingFor: 'Twins/mole' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'warning', title: 'THIAMINE FIRST', text: 'Give thiamine BEFORE any glucose-containing fluid (100 mg IV slow) - Wernicke prevention.' }],
      firstLine: [
        { kind: 'doseCard', drug: 'IV fluid rehydration', dose: '1 L Hartmann/NS over 2-4 h cycles; KCl added per protocol once urine output confirmed', route: 'IV', frequency: 'Until rehydrated then maintenance', notes: ['Correct Na slowly if severe hyponatraemia'], sourceId: 'who-anc-2016-updates' },
        { kind: 'doseCard', drug: 'Thiamine', dose: '100 mg IV slow daily while vomiting persists', route: 'IV/PO', frequency: 'Daily', duration: 'Until eating again', sourceId: 'who-anc-2016-updates' },
        { kind: 'doseCard', drug: 'Pyridoxine +/- doxylamine', dose: 'Pyridoxine 10-25 mg TDS (+ doxylamine 12.5-25 mg nocte)', route: 'PO', frequency: 'TDS/nocte', notes: ['First-line pharmacotherapy'], sourceId: 'who-anc-2016-updates' },
        { kind: 'doseCard', drug: 'Antiemetic ladder additions', dose: 'Ondansetron 4-8 mg q8h PO/IV; promethazine 12.5-25 mg q8h; metoclopramide 10 mg q8h (EPSE caution young women); domperidone alternative', route: 'PO/IV/IM', frequency: 'Per agent', notes: ['Rotate/add rather than max-out single agent'], sourceId: 'who-anc-2016-updates' },
      ],
      alternativesFirstLine: [{ kind: 'list', items: ['Acupressure/ginger adjunct evidence modest', 'Steroids (methylprednisolone) LAST resort refractory cases - taper quickly, avoid T1 prolonged use'] }],
      definitiveTreatment: [{ kind: 'text', text: 'Symptoms typically improve substantially by 16-20 wks; nutritional rehabilitation is the endpoint.' }],
      monitoring: [{ kind: 'table', headers: ['Domain', 'Schedule'], rows: [
        ['Weights', 'Each visit/admission'],
        ['Electrolytes', 'Daily during IV phase'],
        ['Nutritional intake diary', 'Daily'],
        ['VTE risk', 'Assess at each immobile admission'],
      ] }],
      responseAssessment: [{ kind: 'list', items: ['Vomiting episodes falling; oral tolerance rising; ketones clearing; weight stabilising'] }],
      treatmentFailure: [{ kind: 'list', items: ['Multiagent failure -> enteral feeding (NG) consideration, parenteral nutrition rarely; TPN-line sepsis risks discussed'] }],
      secondLine: [{ kind: 'list', items: ['Gastroenterology/dietitian co-management refractory'] }],
      rescue: [{ kind: 'text', text: 'Wernicke suspected: IMMEDIATE thiamine + neurology; termination counselling offered only in extreme life-threatened refractory cases (documented multidisciplinary).' }],
      procedures: [{ kind: 'text', text: 'NG feeding technique per nutrition team.' }],
      escalation: [{ kind: 'list', items: ['Admission criteria: dehydration needing IV, ketonuria+, electrolyte derangement, weight loss, social unsafety'] }],
      complications: [
        { name: 'Wernicke encephalopathy', management: [{ kind: 'text', text: 'Thiamine urgently; avoid glucose-first errors' }] },
        { name: 'Mallory-Weiss tears', management: [{ kind: 'text', text: 'Usually self-limited; PPI; assess bleeding' }] },
        { name: 'VTE', management: [{ kind: 'text', text: 'LMWH prophylaxis for immobile admissions (risk assessment)' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['Discharge with antiemetic plan + early-return rules', 'Psychological support (HG distress is real)', 'Recurrence anticipation next pregnancy (~15-20%)'] }],
    },
    sourceIds: ['who-anc-2016-updates'],
  },

  {
    id: 'icp',
    title: 'Intrahepatic Cholestasis of Pregnancy',
    category: 'medical-disorders',
    tags: ['icp', 'itching', 'bile-acids', 'ursodeoxycholic'],
    status: 'outdated',
    version: 1,
    reviewerNote: 'RCOG GTG43 delivery thresholds are dated; newer data (PPS trial) individualise timing. Flagged for specialist re-audit.',
    regionPriority: 'international-first',
    summary: 'Pruritus (palms/soles) + raised bile acids WITHOUT rash/other liver cause. Ursodeoxycholic acid improves itch (not clearly outcomes). Fetal risk rises with bile acids >100 µmol/L; individualise delivery timing ~35-38+ wks by severity.',
    definition: 'Impaired bile flow in late pregnancy: pruritus + fasting serum bile acids >19 µmol/L (or ALT/AST rise) resolving postpartum.',
    redFlags: ['Bile acids >=100 µmol/L (highest stillbirth band)', 'Jaundice', 'Abnormal CTG', 'Steatorrhoea/vitamin-K deficiency signs'],
    initialAssessment: [{ kind: 'steps', steps: [
      'Fasting serum bile acids + LFTs',
      'Exclude other causes: viral hepatitis serology, gallstones US, PET overlap labs',
    ] }],
    investigations: [
      { test: 'Bile acids (fasting)', lookingFor: 'Severity stratification axis' },
      { test: 'ALT/AST + GGT', lookingFor: 'Pattern support' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'text', text: 'Not acute unless fetal compromise.' }],
      firstLine: [
        { kind: 'doseCard', drug: 'Ursodeoxycholic acid', dose: '500 mg BD (titrate to 15 mg/kg/day)', route: 'PO', frequency: 'BD', duration: 'Until birth', notes: ['Improves pruritus; perinatal benefit uncertain - counsel honestly'], sourceId: 'rcog-gtg43-icp' },
        { kind: 'doseCard', drug: 'Vitamin K', dose: '10 mg PO daily if prolonged PT/coagulopathy concern', route: 'PO', frequency: 'Daily', duration: 'Until birth', sourceId: 'rcog-gtg43-icp' },
        { kind: 'info', title: 'Delivery timing', text: 'Individualised ~35-38+0 wks by bile-acid banding and local policy; >=100 µmol/L often earlier (~35-37). Document shared decision (induction risks vs stillbirth risk).' },
      ],
      definitiveTreatment: [{ kind: 'text', text: 'Birth resolves; LFTs/bile acids normalize within weeks postpartum.' }],
      monitoring: [{ kind: 'list', items: ['Weekly bile acids/LFTs', 'CTG/growth surveillance per unit policy (esp. severe band)'] }],
      responseAssessment: [{ kind: 'list', items: ['Itch improvement (UDCA); stable labs'] }],
      treatmentFailure: [{ kind: 'list', items: ['Escalating acids -> expedite birth decision'] }],
      secondLine: [{ kind: 'list', items: ['Rifampicin adjunct (rare, specialist)'] }],
      rescue: [{ kind: 'text', text: 'Coagulopathy near birth: vitamin K IV + FFP availability.' }],
      procedures: [{ kind: 'text', text: 'Induction reasonable; continuous CTG in labour common practice.' }],
      escalation: [{ kind: 'list', items: ['Hepatology if jaundice severe/atypical features'] }],
      complications: [
        { name: 'Stillbirth (band-related)', management: [{ kind: 'text', text: 'Timed-birth strategy mitigates; document reasoning' }] },
        { name: 'Postpartum persistence', management: [{ kind: 'text', text: 'Recheck LFTs 6 wks; investigate chronic liver disease if abnormal' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['LFT normalization confirmation', 'Recurrence 60-90% next pregnancies - early bile-acid plan', 'Avoid oestrogen-containing contraception until resolved'] }],
    },
    sourceIds: ['rcog-gtg43-icp'],
  },

  {
    id: 'asthma-epilepsy-cardiac-ckd-autoimmune',
    title: 'Chronic Medical Disorders Quick-Reference (asthma · epilepsy · cardiac · CKD · SLE/APS)',
    category: 'medical-disorders',
    tags: ['asthma', 'epilepsy', 'cardiac-disease', 'ckd', 'sle', 'aps'],
    status: 'review',
    version: 1,
    reviewerNote: 'Condensed index module - each domain deserves full expansion in v1.1 content cycle.',
    regionPriority: 'international-first',
    summary: 'Continuity beats novelty: keep effective pre-pregnancy regimens (with teratogen switches), monitor organ function each trimester, plan birth in appropriately equipped units.',
    specialSituations: [
      { kind: 'table', headers: ['Condition', 'Pregnancy-critical points'], rows: [
        ['Asthma', 'ICS safe & essential - undertreatment kills; LABA continue; montelukast OK; acute attack treated FULLY (O2+SABA+steroids); fetal hypoxia is the danger'],
        ['Epilepsy', 'NEVER abrupt-stop ASM; lamotrigine/levetiracetam favoured (levels fall - increase doses!); valproate avoid where possible; folic acid 5 mg/day; single-drug lowest-effective principle'],
        ['Cardiac disease', 'mWHO classification drives unit level; NYHA reviews each trimester; endocarditis prophylaxis per lesion policy; anticoagulation switches managed by cardiology; watch heart-failure window 28-34 wks + postpartum'],
        ['CKD', 'Stage-linked risks; BP target <140/90 with labetalol/nifedipine; aspirin; nephrology co-care; ACEi/ARB stopped pre-conception (enalapril OK postpartum/lactation)'],
        ['SLE', 'Plan conception in quiet disease (hydroxychloroquine CONTINUE - protective); azathioprine/calcineurin-inhibitors compatible; mycophenolate/cyclophosphamide STOP; neonatal lupus (anti-Ro) surveillance; flares vs PE differentiation'],
        ['APS', 'Obstetric APS: aspirin + prophylactic LMWH from positive test; thrombotic APS: therapeutic LMWH; platelet watch'],
      ] },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'text', text: 'Domain-specific emergencies follow their modules; this page is a continuity checklist.' }],
      firstLine: [{ kind: 'list', items: [
        'Booking: medication reconciliation against TERATOGEN list; specialist letters obtained',
        'Trimester checkpoints: disease activity labs + organ function',
        'Birth planning: unit capability matched to mWHO/CKD stage/SLE activity',
        'Postpartum: flare windows (SLE), medication continuation, lactation compatibility table applied',
      ] }],
      monitoring: [{ kind: 'list', items: ['Individualised per condition above'] }],
      escalation: [{ kind: 'list', items: ['Joint clinics (obstetric-medicine) strongly recommended'] }],
      complications: [{ name: 'Flare vs PE confusion', management: [{ kind: 'text', text: 'Complement levels, anti-dsDNA, proteinuria trend differentiate' }] }],
      postTreatmentCare: [{ kind: 'list', items: ['6-week specialist review each condition'] }],
    },
    sourceIds: ['who-anc-2016-updates'],
  },
]
