import type { DiseaseTopic } from '../types'

/* ============================================================
   MEDICAL DISORDERS IN PREGNANCY — Part A
   Sources: WHO ANC updates (IFA), FOGSI context, RCOG GTG76 thyroid.
   Verification levels set honestly per topic. Checked 2026-08-23.
   ============================================================ */

export const MEDICAL_TOPICS_A: DiseaseTopic[] = [
  {
    id: 'gdm',
    title: 'Gestational Diabetes Mellitus',
    category: 'medical-disorders',
    tags: ['gdm', 'ogtt', 'metformin', 'insulin', 'hyperglycaemia'],
    aliases: ['gestational diabetes', 'sugar in pregnancy'],
    status: 'clinically-verified',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'india-first',
    summary: 'India screens universally (DIPSI/WHO). Diet+exercise first; metformin where appropriate; insulin when targets missed. Steroids raise glucose - plan monitoring.',
    definition: 'Any hyperglycaemia first recognised in pregnancy (WHO/DIPSI: 75 g OGTT 2-h >=140 mg/dL common Indian threshold; ADA/NICE cutoffs differ - jurisdiction recorded per recommendation).',
    redFlags: ['Ketones + vomiting -> DKA/starvation ketosis', 'Macrosomia/polyhydramnios = control failure', 'Reduced movements late pregnancy', 'Steroid-course glucose spikes'],
    initialAssessment: [{ kind: 'steps', steps: [
      'Screen: universal 75 g OGTT at booking (DIPSI) or 24-28 wks per programme; high-risk earlier',
      'Record WHICH diagnostic framework used',
      'Baseline HbA1c if early diagnosis (differentiate pregestational), CBC, renal/liver profile',
      'Fetal dating/growth baseline',
    ] }],
    investigations: [
      { test: '75 g OGTT', lookingFor: 'Diagnosis per framework' },
      { test: 'SMBG log', lookingFor: 'FBG <95 mg/dL; postprandial targets' },
      { test: 'Urine ketones when ill/hyperglycaemic', lookingFor: 'Starvation vs DKA' },
      { test: 'Growth scans q4 wks from 28-32', lookingFor: 'Trajectories' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'text', text: 'Acute presentations -> dka-pregnancy topic.' }],
      firstLine: [
        { kind: 'list', items: [
          'STEP 1 (all): nutrition therapy + 30 min/day exercise; Indian-diet carbohydrate distribution counselling',
          'STEP 2 (1-2 wks diet fails OR FBG >126): METFORMIN 500 mg OD titrated to 500-1000 mg BD-TDS',
          'STEP 3: ADD INSULIN when still above target or metformin unsuitable (NPH-based typical protocols)',
        ] },
        { kind: 'doseCard', drug: 'Insulin initiation (typical)', dose: '~0.3 U/kg/day split: half NPH bedtime + half rapid-acting divided prandial; titrate by pattern q3 days', route: 'SC', frequency: 'Per split', duration: 'Through pregnancy', notes: ['Requirements rise each trimester', 'Hypoglycaemia education'], sourceId: 'who-anc-2016-updates' },
      ],
      alternativesFirstLine: [{ kind: 'list', items: ['Glibenclamide limited contexts - neonatal hypoglycaemia caution'] }],
      definitiveTreatment: [{ kind: 'text', text: 'Birth resolves GDM; timed birth 38-39 wks insulin-requiring/macrosomia; 39-40 diet-controlled.' }],
      monitoring: [
        { kind: 'table', headers: ['Domain', 'Schedule'], rows: [
          ['SMBG', 'Daily until stable then pattern-testing'],
          ['Growth scans', 'q4 wks from 28-32'],
          ['BP/proteinuria', 'Each visit'],
          ['During steroid courses', 'q4-6h CBG + correction plan'],
        ] },
        { kind: 'warning', title: 'Intrapartum/postpartum rules', text: 'Labour insulin-requiring: dextrose-insulin infusion (1 U per 4 g glucose, ~1 U/h); hourly CBG 72-126 mg/dL. Post-birth STOP pregnancy insulin; fasting glucose day 2; OGTT at 6-12 wks; annual lifetime screening.' },
      ],
      responseAssessment: [{ kind: 'list', items: ['Targets met without severe hypoglycaemia', 'Normal growth trajectory'] }],
      treatmentFailure: [{ kind: 'list', items: ['Postprandial excursions -> intensify prandial insulin', 'Dawn phenomenon -> adjust basal'] }],
      secondLine: [{ kind: 'list', items: ['Basal-bolus intensification; CGM for problem patterns'] }],
      rescue: [{ kind: 'text', text: 'Severe hypoglycaemia: 50% dextrose 50 mL IV / glucagon IM.' }],
      escalation: [{ kind: 'list', items: ['Endocrinology co-management', 'NICU aware for LGA babies'] }],
      complications: [
        { name: 'Shoulder dystocia', management: [{ kind: 'text', text: 'Emergency readiness at birth' }] },
        { name: 'Neonatal hypoglycaemia', management: [{ kind: 'text', text: 'Early feeding + checks' }] },
        { name: 'Future T2DM risk', management: [{ kind: 'text', text: 'Postpartum OGTT + annual screening + lifestyle programme' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['Postpartum OGTT 6-12 wks (non-pregnant criteria)', 'Lactation support', 'Contraception planning'] }],
    },
    algorithm: [
      { id: 'g1', label: 'OGTT positive (framework recorded)', type: 'start' },
      { id: 'g2', label: 'Nutrition + exercise', type: 'action', next: [{ to: 'g3' }] },
      { id: 'g3', label: 'Targets met 1-2 wks?', type: 'decision', next: [{ to: 'g4', edgeLabel: 'YES' }, { to: 'g5', edgeLabel: 'NO' }] },
      { id: 'g5', label: 'Metformin titration', type: 'action', tone: 'warn', next: [{ to: 'g6' }] },
      { id: 'g6', label: 'Targets met?', type: 'decision', next: [{ to: 'g4', edgeLabel: 'YES' }, { to: 'g7', edgeLabel: 'NO' }] },
      { id: 'g7', label: 'ADD INSULIN', type: 'end', tone: 'danger' },
      { id: 'g4', label: 'Surveillance -> timed birth', type: 'end', tone: 'ok' },
    ],
    sourceIds: ['who-anc-2016-updates'],
  },

  {
    id: 'pregestational-diabetes',
    title: 'Pregestational Diabetes (T1/T2)',
    category: 'medical-disorders',
    tags: ['type1', 'type2', 'hba1c', 'retinopathy', 'nephropathy'],
    status: 'published',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'international-first',
    summary: 'Preconception HbA1c <=7% minimises malformations. Baseline retina/kidney, stop teratogens (ACEi/statins), insulin-centric care, tight intrapartum glucose.',
    definition: 'Type 1/Type 2 diabetes predating conception.',
    redFlags: ['DKA (lower thresholds pregnant!)', 'Severe hypoglycaemia', 'Retinopathy progression', 'Nephropathy/oligohydramnios', 'Fetal compromise'],
    initialAssessment: [{ kind: 'steps', steps: [
      'Preconception ideal: HbA1c, retinal screen, ACR/eGFR, medication switch list (STOP ACEi/ARB/statins)',
      'Unscreened pregnancy confirmation: same panel urgently',
      'Aspirin prophylaxis + fetal echo ~19-22 wks',
    ] }],
    investigations: [
      { test: 'HbA1c monthly', lookingFor: '<=48-53 mmol/mol balancing hypos' },
      { test: 'Retinal screening', lookingFor: 'Progression needing laser' },
      { test: 'eGFR/ACR monthly if nephropathy', lookingFor: 'Staging' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'warning', title: 'Sick-day rules', text: 'Never omit insulin when vomiting/ill; ketones q4h; early contact prevents DKA deaths.' }],
      firstLine: [
        { kind: 'doseCard', drug: 'Intensive insulin (basal-bolus/pump)', dose: 'Individualised; expect 2-3x prepregnancy needs by T3', route: 'SC', frequency: 'Basal+prandial corrections', notes: ['CGM beneficial', 'Hypo-unawareness education'], sourceId: 'who-anc-2016-updates' },
        { kind: 'info', title: 'Birth timing', text: 'Tight control uncomplicated: 37+0-38+6 individualised; vascular/nephropathy earlier (34-37).' },
      ],
      definitiveTreatment: [{ kind: 'text', text: 'Birth + immediate postpartum insulin reduction 25-50% (written pre-birth plan).' }],
      monitoring: [{ kind: 'table', headers: ['Parameter', 'Frequency'], rows: [
        ['Glucose review', 'Weekly-fortnightly clinic'],
        ['Renal', 'Monthly if nephropathy'],
        ['Growth/fluid', 'q4 wks'],
        ['BP/proteinuria', 'Every visit'],
      ] }],
      responseAssessment: [{ kind: 'list', items: ['Acceptable A1c trend; no severe hypos; normal surveillance'] }],
      treatmentFailure: [{ kind: 'list', items: ['Intensify regimen; endocrinology; consider admission stabilisation'] }],
      secondLine: [{ kind: 'list', items: ['Automated delivery systems where accessible'] }],
      rescue: [{ kind: 'text', text: 'DKA pathway; hypo protocol.' }],
      procedures: [{ kind: 'text', text: 'Lower CS threshold for EFW >4-4.25 kg - counsel explicitly.' }],
      escalation: [{ kind: 'list', items: ['Joint diabetes-obstetric clinics', 'ICU for crises'] }],
      complications: [
        { name: 'DKA', management: [{ kind: 'text', text: 'Dedicated module' }] },
        { name: 'Congenital anomalies', management: [{ kind: 'text', text: 'Detailed scan + echo; counselling' }] },
        { name: 'Neonatal hypoglycaemia', management: [{ kind: 'text', text: 'Paediatric protocol' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['De-escalation plan executed immediately', 'Breastfeeding hypo precautions', 'Contraception: POP/implant/IUD excellent'] }],
    },
    sourceIds: ['who-anc-2016-updates'],
  },

  {
    id: 'thyroid-pregnancy',
    title: 'Thyroid Disease in Pregnancy',
    category: 'medical-disorders',
    tags: ['hypothyroidism', 'levothyroxine', 'graves', 'ptu', 'thyroid-storm'],
    status: 'review',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'international-first',
    summary: 'Levothyroxine rises ~30% on conception confirmation; titrate to trimester-specific TSH q4-6 wks. Graves: PTU preferred first trimester then switch carbimazole. Storm = PTU load + beta-blockade + steroids + ICU.',
    definition: 'Hypothyroidism, Graves/toxic nodular disease, thyroiditis in pregnancy.',
    redFlags: ['THYROID STORM (fever+tachyarrhythmia+CNS signs)', 'Preterm labour with uncontrolled thyrotoxicosis', 'TRAb-positive neonatal thyrotoxicosis anticipation'],
    initialAssessment: [{ kind: 'steps', steps: [
      'TSH + FT4 (trimester-specific ranges or ULN 4.0 approach)',
      'TRAb in Graves (neonatal planning)',
      'Eye disease documentation',
    ] }],
    investigations: [
      { test: 'TFTs q4-6 wks', lookingFor: 'Titration axis' },
      { test: 'TRAb', lookingFor: 'Fetal risk stratification' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'text', text: 'Storm: stabilise BEFORE any delivery decision unless obstetric indication forces it.' }],
      firstLine: [
        { kind: 'doseCard', drug: 'Levothyroxine', dose: 'Increase usual dose ~30% at pregnancy confirmation (e.g., 100->130 mcg); titrate TFTs q4-6 wks', route: 'PO fasting', frequency: 'OD', duration: 'Through lactation (compatible)', notes: ['Separate from iron by 4 h'], sourceId: 'rcog-gtg76-thyroid' },
        { kind: 'doseCard', drug: 'Propylthiouracil', dose: '50-150 mg BD-TDS titrated; FIRST TRIMESTER agent of choice', route: 'PO', frequency: 'BD-TDS', duration: 'Switch to carbimazole after T1 for long-term', contraindications: ['Prior PTU hepatitis', 'Neutropenia'], adverseEffects: ['Agranulocytosis (fever/sore-throat rule!), hepatotoxicity'], monitoring: ['TFTs q4 wks stable', 'CBC urgently if febrile/oral ulcers'], sourceId: 'rcog-gtg76-thyroid' },
        { kind: 'doseCard', drug: 'Carbimazole', dose: '5-20 mg daily titration (post-T1 preferred)', route: 'PO', frequency: 'OD-BD', notes: ['Embryopathy window is T1', 'Block-replace strategy for high-demand cases'], sourceId: 'rcog-gtg76-thyroid' },
      ],
      alternativesFirstLine: [{ kind: 'list', items: ['Propranolol short-term symptom bridge', 'Radioiodine ABSOLUTELY contraindicated'] }],
      definitiveTreatment: [{ kind: 'text', text: 'Thyroidectomy rarely (compressive/refractory) - best second trimester.' }],
      monitoring: [{ kind: 'list', items: ['TFTs q4-6 wks', 'High TRAb: fetal HR/growth/goitre surveillance', 'Postpartum flare anticipation'] }],
      responseAssessment: [{ kind: 'list', items: ['Euthyroid maintenance'] }],
      treatmentFailure: [{ kind: 'list', items: ['Adherence check; absorption interference (iron!); endocrine referral'] }],
      secondLine: [{ kind: 'list', items: ['Specialist referral refractory disease'] }],
      rescue: [{ kind: 'text', text: 'Storm bundle: PTU 500-1000 mg load via NG, propranolol/esmolol infusion, hydrocortisone 100 mg q8h, ICU support, cooling.' }],
      escalation: [{ kind: 'list', items: ['ICU storm', 'Neonatal team alert TRAb+ mothers'] }],
      complications: [
        { name: 'Fetal/neonatal thyrotoxicosis', management: [{ kind: 'text', text: 'Fetal HR surveillance; paediatric ready at birth' }] },
        { name: 'Postpartum thyroiditis', management: [{ kind: 'text', text: 'TSH 6-12 wks postpartum; manage phases' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['Postpartum TFT schedule', 'Breastfeeding-compatible dosing (monitor infant clinically)'] }],
    },
    sourceIds: ['rcog-gtg76-thyroid'],
  },

  {
    id: 'anaemia-iron-deficiency',
    title: 'Anaemia in Pregnancy (Iron/Folate/B12)',
    category: 'medical-disorders',
    tags: ['anaemia', 'iron', 'iv-iron', 'ifa', 'thalassaemia-screen'],
    aliases: ['low hemoglobin', 'IDA'],
    status: 'clinically-verified',
    version: 1,
    lastVerifiedAt: '2026-08-23',
    regionPriority: 'india-first',
    summary: 'Hb <11 g/dL (WHO). Prophylaxis IFA 60 mg elemental iron + 400 mcg folate daily. Treat IDA decisively: alternate-day oral optimises absorption; IV iron for intolerance/severe/late. Screen haemoglobinopathy before reflex "IDA" labels in microcytosis.',
    definition: 'WHO pregnancy anaemia <11.0 g/dL; severe <7.0.',
    redFlags: ['Hb <7 or cardiac symptoms -> transfusion consideration + IV iron', 'Unresolved bleeding source stacking PPH risk', 'Microcytosis with normal-high ferritin -> thalassaemia workup FIRST'],
    initialAssessment: [{ kind: 'steps', steps: [
      'CBC indices + smear',
      'Iron studies (ferritin +/- TSAT)',
      'B12/folate when macrocytic/mixed',
      'HPLC/electrophoresis where indicated',
    ] }],
    investigations: [
      { test: 'Ferritin', lookingFor: '<30 ng/mL supports absolute deficiency' },
      { test: 'HPLC', lookingFor: 'Beta-thal trait / variants' },
    ],
    treatment: {
      immediateStabilization: [{ kind: 'list', items: ['Symptomatic severe anaemia near birth: transfuse (target ~8-9 pre-delivery context) + treat cause simultaneously'] }],
      firstLine: [
        { kind: 'doseCard', drug: 'Oral elemental iron (treatment)', dose: '60-120 mg elemental iron daily OR ALTERNATE-DAY (better absorption, fewer effects); vitamin C co-ingestion; avoid tea/coffee 2 h', route: 'PO', frequency: 'Daily/alternate day', duration: 'Until Hb normal THEN 3 months store repletion', adverseEffects: ['GI upset - switch to alternate-day'], sourceId: 'who-anc-2016-updates' },
        { kind: 'doseCard', drug: 'IV iron (FCM / iron sucrose)', dose: 'Deficit-calculated ( Ganzoni or simplified weight-based): FCM up to 15 mg/kg per session (max 1000-1500 mg course); sucrose 200 mg per session cumulative', route: 'IV', frequency: 'Per preparation protocol', duration: 'Deficit-based', contraindications: ['Active infection (defer)', 'Known hypersensitivity', 'T1 avoidance convention'], adverseEffects: ['Infusion reactions - observe 30 min', 'FCM: rare hypophosphataemia'], monitoring: ['Hb recheck 2-4 wks'], sourceId: 'who-anc-2016-updates' },
        { kind: 'doseCard', drug: 'Prophylactic IFA (WHO/national)', dose: '60 mg elemental iron + 400 mcg folate daily from 2nd trimester (weekly intermittent option where daily intolerable & prevalence <20%)', route: 'PO', frequency: 'Daily', duration: 'Pregnancy + postpartum per programme', sourceId: 'who-anc-2016-updates' },
      ],
      definitiveTreatment: [{ kind: 'text', text: 'Store repletion + cause correction (bleeding, diet, deworming per programme).' }],
      monitoring: [{ kind: 'list', items: ['Hb 2-4 wks after change', 'Individualised transfusion thresholds'] }],
      responseAssessment: [{ kind: 'list', items: ['>=1 g/dL per fortnight oral; symptom improvement'] }],
      treatmentFailure: [{ kind: 'list', items: ['Non-response: adherence, blockers, occult loss, alternative dx -> switch IV'] }],
      secondLine: [{ kind: 'list', items: ['IV pathway; haematology referral uncertainty'] }],
      rescue: [{ kind: 'text', text: 'Cardiac-compromised: slow PRBC transfusion; equipped-unit birth planning.' }],
      escalation: [{ kind: 'list', items: ['Haemoglobinopathy pregnancies -> haematology co-care'] }],
      complications: [
        { name: 'PPH amplification', management: [{ kind: 'text', text: 'Correct BEFORE birth - strongest modifiable PPH-death factor locally' }] },
        { name: 'PTB/LBW associations', management: [{ kind: 'text', text: 'Timely correction reduces risk' }] },
      ],
      postTreatmentCare: [{ kind: 'list', items: ['Iron continues 3 months postpartum', 'Family haemoglobinopathy screening'] }],
    },
    sourceIds: ['who-anc-2016-updates'],
  },
]
